### ISSUE TITLE
can I block a specific model when creating screenshots using mirv_streams?

### ISSUE THREAD

**Issue by hamitsui** [advancedfx/advancedfx#1]
Can I somehow block a specific player model by id when creating world streams?
need to record a separate stream specific model which would be separate from other models.

**Comment by dtugend** [comment]
Yes, you can.

Just find the entity handles you want to hide or draw with mirv_streams picker and set up your standard streams actions and actionFilter accordingly:

Here is a related tutorial I made, that you might find helpful:

**mirv_streams - picker - Hiding materials / entites and special effects**
https://youtu.be/aLxHUIOpGcU

**Comment by dtugend** [comment]
Can we close this issue, or do you have further questions related to that?

**Comment by hamitsui** [comment]
No thanks that's all i need! You can close the ticket now. Thank you!

**Comment by dtugend** [comment]
I am reopening this issue, because I found a bug I made in HLAE 2.29.0 that causes entity handle based actionFilter to not work sometimes.

Until it is fixed, please use HLAE 2.28.0 or older: https://github.com/ripieces/advancedfx/releases/tag/v2.28.0

I will notify you here when it has been fixed / close the issue again then.

**Comment by hamitsui** [comment]
alright, thank's for the notice, I'll wait for the next update.

**Comment by dtugend** [comment]
Okay, fixed, please update to
[HLAE 2.30.1 (2017-06-02T20:28Z) or newer](https://github.com/ripieces/advancedfx/releases/latest)
