### ISSUE TITLE
I can't record using the AfxHookSourse dll.

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#11]
Whenever I try to record by typing "mirv_streams record name "path"" and "mirv_streams record name start" in console, It doesn't do anything. Yet previously it started recording the way it was supposed to. I didnt change anything and I dont know how to fix this..

**Comment by dtugend** [comment]
Are you getting any error messages when launching with HLAE?
If so, please read them, they sometimes even contain possible solution hints.

**Comment by dtugend** [comment]
Also I recommend using File -> Launch CS:GO instead of Custom Loader, this will avoid some common mistakes.

**Comment by ghost** [comment]
No error message, it just does completely nothing

**Comment by dtugend** [comment]
Are you using Customloader? If so please post a screenshot of it and try the other option as said above.

**Comment by xNWP** [comment]
It's a syntax issue, the command to start recording is mirv_streams record start
NOT mirv_streams record name start

Let me know if that fixes it :)

**Comment by ghost** [comment]
Ohh this must have been changed in an update or something. I used to do it WITH name in it and it worked fine. Thanks though!

**Comment by xNWP** [comment]
It's always been that way, your command/reference must have been botched at some point, when you sent the second command mirv_streams record name start you were actually renaming the recording to start, instead of actually running the start command. If you have trouble finding a command you can type mirv_streams and it will print all the commands for it, then just work your way down, you'll quickly find the command for recording :)

Glad it's all working now!

**Comment by dtugend** [comment]
Solved I guess.
