### ISSUE TITLE
mirv_vpanel possible panel names

### ISSUE THREAD

**Issue by hellkama** [advancedfx/advancedfx#117]
Are the panel names that are available for use with mirv_vpanel hide/show documented anywhere?

This command could have some potential for customizing the hud for recording videos.

**Comment by dtugend** [comment]
1) This feature only includes the old vpanels, not those in Panorama UI, regarding Panorama UI see https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI.

2) CS:GO still uses several of those old panels (i.e. for the text chat). You can get a list of names by using `vgui_drawtree` be aware the names are case-sensitive. Also make sure to tick hidden panels to see hidden panel names as well. Attention: Some panels must be forced to be drawn / hidden, because the engine updates the visibility every frame, using mirv_streams stream properties attachCommands and detachCommands are perfectly suited for that, just add a "normal" stream and use these properties to set you mirv_vpanel commands and put it in preview:
```
mirv_streams add normal myNorm
mirv_streams edit myNorm attachCommands mirv_vpanel hide Name1; mirv_vpanel hide Name2
mirv_streams edit myNorm detachCommands mirv_vpanel show Name1; mirv_vpanel show Name2 // only required if you have multiple streams
mirv_streams preview myNorm 
```

**Comment by dtugend** [comment]
I also want to add that you have to go through the tree in the vgui_drawtree UI panel, because most are not clickable and thus can not be found with the hovering feature.
