### ISSUE TITLE
The sound file is never any longer than 0.1 seconds.

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#12]
When recording, the included sound file is never any longer than 0.1 seconds and it's size is never any larger than 1kb. Any way to get the sound? It's always been this way for me, but as I never needed it before, I didn't bother fixing it.

**Comment by dtugend** [comment]
Which HLAE version are you using?
Startmovie is a CS:GO console command that Valve accidentally broke with the 7/7/2017 - they aware of that by now, but not sure when they will fix it.
You an use mirv_streams with the latest HLAE version (2.35.1 or newer) to get the audio on probably most Windows operating systems:
https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_streams#recording-example

**Comment by xNWP** [comment]
Audio is working fine for me, make sure you're using the latest version of HLAE, which operating system are  you're using (i.e. Windows 7, 8, 8.1, 10)

**Comment by ghost** [comment]
I did get audio to work now, I tried what ripieces mentioned. However, now audio worked, but the tga files didnt. Also, when I tried to use the audio with a previous recording of the same footage, it wasnt in sync. The audio was way shorter than the video yet it is the same exact round. Any thoughts?

**Comment by dtugend** [comment]
You need to add a stream to record, by default it will only record audio, see the page I linked, for beginners adding a "normal" stream will do.

Don't forget to set host_framerate before recording.

Don't forget to set the host_framerate as FPS when importing the TGA files in your video editor, otherwise the audio and video will most likely not match at all.

Also don't mix video and audio from different recordings, in CS:GO the recordings will usually be a bit different each time.

**Comment by xNWP** [comment]
Mind letting everyone know if dom's suggestion worked, so that the issue may be closed :)

**Comment by dtugend** [comment]
Closing this due to lacking feedback on the suggested solution(s), feel free to report back later.
