### ISSUE TITLE
how can i use camera path when the time is stop

### ISSUE THREAD

**Issue by yellowfisherz** [advancedfx/advancedfx#131]
i want when the time is stop 
the camera path can be use(?)
the camera can move up~

**Comment by dtugend** [comment]
Can you try to rephrase the question please, it's not really understandable?

**Comment by yellowfisherz** [comment]
> 你可以尝试重新解释这个问题吗，这不是真的可以理解吗？

hmmm,i mean.
When the camera is moving, everyone is still.(when the demo not play)
I want make the path work when the demo not play.

**Comment by dtugend** [comment]
I am sorry, HLAE does not properly support that yet.

However you can use a very high `host_framerate` (e.g. 10000 / 100000 / 1000000).
You might also want to set `mirv_fix physicsMaxFps` 10000 / 100000 / 1000000 in order to avoid some bugs: https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_fix#mirv_fix-physicsmaxfps

The idea is you make your mirv_campath at normal speed and then use `mirv_campath edit duration` (in seconds) to scale it to a very short time: https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_campath#scaling-the-duration-of-the-path

Edit: This is also important for high FPS: https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos

**Comment by dtugend** [comment]
Hi, there's a new HLAE 2.60.0 (2019-02-03T05:59Z): https://github.com/advancedfx/advancedfx/releases

Use `mirv_time mode pausedTime` - Campaths etc will keep running at host_framerate, even when demo is paused with demo_pause.

**Comment by yellowfisherz** [comment]
> 嗨，有一个新的HLAE 2.60.0（2019-02-03T05：59Z）：[https](https://github.com/advancedfx/advancedfx/releases)：[//github.com/advancedfx/advancedfx/releases](https://github.com/advancedfx/advancedfx/releases)
> 
> 使用`mirv_time mode pausedTime`- Campaths等将继续在host_framerate上运行，即使使用demo_pause暂停demo也是如此。

yes!!!!!!!!!!!
i want this function!!!!!!!!!!!
i love youuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu!!!!!!!!!!!!
