### ISSUE TITLE
new update doesnt work

### ISSUE THREAD

**Issue by smoothda** [advancedfx/advancedfx#140]
it highlights my kills in a box but no longer hides everyone elses. nice job fix this right away.

**Comment by xNWP** [comment]
I certainly hope English isn't your first language and that rudeness was accidental...

With that being said, if you genuinely want support you need to provide more information.

- What effect are you trying to achieve.
- What commands have you entered to achieve this effect.
- What was the actual outcome of the commands (which you vaguely specified).

**Comment by smoothda** [comment]
I'm just trying to highlight my kills in the killfeed and make it so only mine show up. However everyone elses kills show up as well. English is my first language. I was frustrated cause either the command for only showing my kills only has changed or it no longer works.
These are the commands I entered and have always entered.
 sv_cheats 1
fov_cs_debug 112
sv_skyname cs_tibet
mirv_listentities isPlayer=1
mirv_deathmsg filter add attackerMatch=!x76561198106761592; victimMatch=!xTrace block=1 lastRule=1
mirv_deathmsg localPlayer x76561198106761592
mp_display_kill_assists 0
mirv_deathmsg lifeTime 60

**Comment by smoothda** [comment]
I managed to get my kills in the feed highlighted though

**Comment by xNWP** [comment]
I understand that when something doesn't work it can be frustrating. But what you need to understand is that this tool is being independently developed by a single developer @dtugend -- This is not his job, he doesn't get paid for it, and has no obligation to maintain the tool whatsoever. Yet he manages to keep it updated within hours of valve updating cs:go (which almost always breaks the tool in some way). That's why it's very disheartening to see you mock his tool, and then demand that a fix be implemented immediately. Especially when in most cases - bugs - are not actually bugs, but users misusing the tool. Which this is the case for you, following your attacker match there is a semi-colon -> **;**
This ends the command prematurely, disallowing the block to be applied. The *localplayer* not working is because you specified an **xUID** -- you need to specify the two digit **userID**.

Verbal abuse will **not** be tolerated towards any advancedfx team members, advancedfx contributors, or GitHub users. I hope in the future you choose to appreciate what is provided to you.

**Comment by smoothda** [comment]
i tried with out semi colons

**Comment by xNWP** [comment]
I just tested all the commands you gave in the exact order you gave them, with the corrections, and it is working as expected on my machine. Ensure that you have the latest version of HLAE (https://github.com/advancedfx/advancedfx/releases/latest), and that your cs:go is updated.

If that fails you may need to send the demo and we can try it ourselves. Otherwise it should be working.

**Comment by smoothda** [comment]
Which hooksource did you use?

**Comment by xNWP** [comment]
You should be launching with "Launch CS:GO" unless you need to inject something else. The hook that is used for CS:GO is AfxHookSource.dll

**Comment by smoothda** [comment]
Oh wait really? I have always launched with custom loader. Alright I just launched it with Launch CSGO it seems to be working for now. Cheers for that

**Comment by xNWP** [comment]
Glad to hear 😁

**Comment by dtugend** [comment]
(<tt>mirv_deathmsg localPlayer</tt> does support <tt>x<b><i>\<XUID\></i></b></tt> though.)

**Comment by xNWP** [comment]
Hmm in my testing it didn't
