### ISSUE TITLE
Error when launching Code: 2000

### ISSUE THREAD

**Issue by bobcaboose** [advancedfx/advancedfx#143]
I get this error here: 
```
AfxError #2000: 
Title: Failed to start injector.
Description: Failed to start injector: C:\Users\dilig\OneDrive\Desktop\\injector.exe
Solution: Check that your Anti Virus did not remove it due to a false positive. If so restore it and add an exception for injector / the HLAE folder.
Inner exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
Happens everything I launch via HLAE. I don't know what it is telling me. Faceit AC and Esea aren't running in the background.

**Comment by dtugend** [comment]
You are probably trying to run HLAE from the .zip file. This is not possible.

Please extract **all** files and folders from the latest HLAE download into an empty folder and then run it from there.

**Comment by bobcaboose** [comment]
I downloaded as a winrar then i extracted the files to my desktop already.
I also ran Hlae perfectly in the past but after the last two updates was when i ran into problems

**Comment by dtugend** [comment]
You Anti-Virus might be deleting the injector.exe, there's two of them, one in x64 subfolder and one in the HLAE.exe folder, for CS:GO the latter one is needed.

Please check if it's there, if not please update you Anti-Virus (e.g. if it's Windows Defender), reboot, re-download and re-extract again and make sure it's not missing.

Updated Windows Defender should be fine, if you use something else you might need  to add an exception for the injector.exe.

I didn't expect you put all those files and folder directly onto the desktop, since it's quite a lot (thought at least into a sub-folder).

**Comment by bobcaboose** [comment]
I extracted to a subfolder, so i have one in the hlae_2_63_2 and another in x64 folders

**Comment by dtugend** [comment]
The error message says it's looking for it on Desktop (`C:\Users\dilig\OneDrive\Desktop\\injector.exe`) and not in that folder, maybe you launched HLAE.exe from wrong location accidentally?

Do you use a shortcut? If so check the shortcut / try the HLAE.exe in the hale_2_63_2 folder.

Also check that the antivirus is not removing the injector.exe after lauching from HLAE.

If that doesn't solve the problem I am available in Discord chat (linked on advandedfx.org support page) on Friday probably.

**Comment by bobcaboose** [comment]
alright, i just had to open hlae from the folder, ty
