### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by gonjay** [advancedfx/advancedfx#161]
x

**Comment by dtugend** [comment]
Easiest solution is to use a skin changer tool:

If you need it for a GOTV demo:
https://github.com/advancedfx/nSkinz/releases

Otherwise use the original source, if you only need it for yourself:
https://github.com/namazso/nSkinz

Be aware that it is a cheat and should not be used on VAC protected servers, just like HLAE.

**Comment by dtugend** [comment]
If the previous reply doesn't fit:

Not sure if I understood your question correctly, if not please clarify.
A weapon is not a simple texture, it's a material with a specifc shader and material properties and multiple textures, just extracting a single texture won't work that easily, you can use GCFScape + VTFEdit to do that though:
http://nemesis.thewavelength.net/index.php?p=25
http://nemesis.thewavelength.net/index.php?c=178

The base weapons material / properties are defined in the items_game.txt text file in the csgo install.
