### ISSUE TITLE
mirv_draw_sv_hitboxes_enable not works and error

### ISSUE THREAD

**Issue by Karaulov** [advancedfx/advancedfx#168]
mirv_draw_sv_hitboxes_enable 1 not works

and if i try to connect to local server, or single player, i got next fatal error: 

```
---------------------------
Game tries to connect
---------------------------
WARNING: You are about to connect to a server.
It is strongly recommended to NOT connect to any server while HLAE is running!

You have the following options now:
Press Yes
	to continue connecting.
Press NO (recommended)
	to abort connecting (HLAE will terminate and lock-up the game).
Cancel
	does the same as No

Do you want to continue connecting?

---------------------------
Да   Нет   Отмена   
---------------------------
```

Latest non beta steam version.

**Comment by dtugend** [comment]
mirv_draw_sv_hitboxes_enable 1

Draws the server side hitbox, thus it won't work in demo / client, it will only work with list servern.

Read more here:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_draw_sv_hitboxes_enable

The error box you get is a not an error, it's a warning, if you are you you want to join a server press yes.

Be aware that if the server has VAC enabled you will get a VAC ban, which is why the warning is in place.

**Comment by Karaulov** [comment]
@dtugend but i tried "New Game" and connect to "Local server", i got this warning and after start game - this cvar not works!

**Comment by Karaulov** [comment]
@dtugend i see this video https://www.youtube.com/watch?v=umEO6BDsEwM and author says 'enter mirv_draw_sv_hitboxes_enable 1" command. I tried but it not works.
https://www.youtube.com/watch?v=umEO6BDsEwM&lc=UgjUb1C87xL3jXgCoAEC.8UOcDnFaqt98UOiwUjZawv

**Comment by Karaulov** [comment]
This not works with rehlds server? (even if running local server?) (For hitboxes debug )

**Comment by dtugend** [comment]
You have to create a "New Game" (Listen Server) for it to work, it doesn't work with dedicated servers, whether hosted on same machine or not.

**Comment by Karaulov** [comment]
@dtugend yes, i tried 'New Game' but it not works too. (I tried latest steam client, and beta steam client, same result)

**Comment by dtugend** [comment]
Thank you for reporting this bug, I will try to check and see what I can do when I have time (probably Friday if there's not too much unexpected events).

**Comment by Karaulov** [comment]
But this not usable and problems with hitboxes can't be fixed, if it imossible use in rehlds...  ((

**Comment by dtugend** [comment]
No, it can not be used with rehlds, you would have to do your own implementation for rehlds.

Sorry ((

I will leave this bug open, to check if ListenServer with official Steam works and if not as you say, then I'll try to fix it for official steam listen server.

**Comment by Karaulov** [comment]
How to add this to rehlds?)))

Possible someone tried add hitboxes to rehlds https://github.com/dreamstalker/rehlds/pull/490

**Comment by dtugend** [comment]
Hi.

* I can't / don't want to help with rehlds.
* The feature works fine, don't forget what is written in the manual: " In order for this to work you need at least another player looking at a player." - The reason is that the **engine doesn't calculate bones when not required**.

I tested it with [Pod Bot](http://podbotmm.bots-united.com/main_pb_page/index.htm) and it works properly that way.

Sorry and with kind regards
