### ISSUE TITLE
Will it be able to record alpha layer?

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#174]
Some want to record a specific layer of HUD and seperate them afterwards. But what I've recorded has greenscreen, looked strange after using keylight. Also, when I'm doing with normal recorded layers, I have to turn the "feathering" and "transhold" higher to get rid of remaining green pixels.

Will be easier if hlae supports alpha layer, isn't it?

**Comment by dtugend** [comment]
Regarding HUD:
https://github.com/advancedfx/advancedfx/wiki/Tutorial%3A-CS%3AGO-Separate-HUD-Stream

Regarding other streams: HLAE used to have alpha layers but that requires replacement vertex and pixel shaders to work properly and since the February 2016 update they got too different from the source code available so that reverse engineering and recompiling them with required modifications takes too much time.

**Comment by dtugend** [comment]
Maybe I could use the same trick as for HUD to render an alpha layer, I will think about that.

**Comment by dtugend** [comment]
It might be possible with a similar trick, but I would need to render 3 streams (game, world, entity) to get something acceptable.

```
game := a * entity + (1-a) * world
entBlackBg = 1 * entity + 0
worldBlackBg = 1 * world + 0

game = a * (entity - world) + world

a * (entity - world) = game -world

a = (game - world) / (entity - world)
```

stock actions (default handling):
noDraw - not drawn in entity, not drawn in world, not drawn in game
draw - drawn in entity, not drawn in world, drawn in game
mask - not drawn in entity, drawn in world, drawn in game

other actions:
need to and possibility to decide for them too

And then I would have to think about something in order to allow people to use all 3 streams rendered, so that they don't go to waste if they need the other streams anyway.

Maybe I could make a meta stream, that uses a another stream to render (compute) alpha, entity and world (select-able whiche ones are output)

Edit: Actually the meta stream only needs a list of actions that will be treated as "Mask" (all others will be treated like "draw")

**Comment by dtugend** [comment]
There's a problem with the method I suggested above:
It doesn't work well (has artifacts), due to numerical problems I should have thought of right away.

Another method similar to the HUD alpha can be used, however it doesn't work well without replacement shaders (which we lost / gave up with the 2016 CS:GO update) :(

I hope I will come up with another solution that doesn't have numerical problems and doesn't need replacement shaders when having time.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.71.0

Check out the new "matte" stream template that comes with that HLAE version or newer.

It's not 100% yet what you wanted, because it has problems with smokes etc, just like the green matteEntity stream :(

Hopefully one day I will find a way.

**Comment by Purple-CSGO** [comment]
Does the problem come from opacity? If an alpha stream automatically changes HUD opacity to 100%, will problems be solved?

**Comment by dtugend** [comment]
By 100% I don't mean the alpha channel, I meant that smokes etc and materials with transparent stuff will have problems / be inaccurate / missing / not applied.

**Comment by dtugend** [comment]
Maybe I found a way to split it pretty perfectly:

----

game = a * matte + (1-a) * other

----

other(x) = (1-a) * other + a * x

other(x) = x => other = x
other(x) < x => other(x) -x < 0 <=> (1-a) * other + a * x  - x < 0 <=> (1-a) * other - (1-a) * x < 0 <=> other - x < 0 <=> other < x
other(x) > x => 0 > x - other(x) <=> 0 > x - (1-a) * other - a * x <=> 0 > (1-a) * x - (1-a) * other <=> x - other < 0 <=> other > x

other(1) - other(0) = a

----

matte(x) = a * matte + (1-a) * x

matte(x) = x => matte = x
matte(x) < x => matte(x) - x < 0 <=> a * matte - a * x < 0 <=> a * (matte - x) < 0 <=> matte - x < 0 <=> matte < x
matte(x) > x => 0 > x - matte(x) <=> 0 > - a * matte + a * x <=> 0 > a * (x-matte) <=> 0 > x - matte <=> matte > x

matte(1) - matte(0) = 1-a

----

Performance estimate (using shaders):

If we want to compute a, matte, other as good as we can, we will need about:

2 + 2 * bits_per_channel render passes.

Meaning for rendering these, if you can 300 FPS with your game, it will run at about 15 FPS, when not dumping to disk + the extra delay for writing 2 streams to disk.

**Comment by dtugend** [comment]
Note to myself: maybe I could use the same trick to render a perfect depth buffer, but that will need 24 passes I think per depth stream = 12.5 FPS for the perfect depth (if you can run your game at 300 FPS)

**Comment by dtugend** [comment]
Not sure yet, if I can do it efficiently in shaders, since the current idea would require to write to to two textures potentially different pixel values at the same time.
Might be tricky in d3d9 without d3d9ex.

**Comment by dtugend** [comment]
It's all wrong, I need to fix it, k thx.

**Comment by dtugend** [comment]
```
https://en.wikipedia.org/wiki/Alpha_compositing

We will be supporting only pre-multiplied alpha output (to support additive):

c_o = c_a + c_b * (1 - a_a)
a_o = a_a + a_b * (1 - a_a)

a_o = c_o / C_o

c_i = a_i * C_i

---

a_o = 1 - (1 - a_a)(1 - a_b)
C_o = (a_a / a_o)* C_a + (1 - (a_a / a_o)) * C_b

---

a_o(0) = 1

Render layer 0 (world) with opaque black background:

C_o(b,0) = a_a(0) * C_a

Render layer 0 (world) with opaque white background:

C_o(w,0) = a_a(0) * C_a + (1 - a_a(0))

a_a(0) = 1 - (C_o(w,0) - C_o(b,0))
C_a(0) = C_o(b,0)

---

a_o(1) = 1 - (1 - a_a(1))*(1 - a_a(0))

Render layer 1 and 2 with opaque black background:

C_o(b,1) = (a_a(1) / a_o(1))* C_a(1) + (1 - (a_a(1) / a_o(1))) * a_o(0) * C_o(b,0)

Render layer 1 and 2 with opaque white background:

C_o(w,1) = (a_a(1) / a_o(1))* C_a(1) + (1 - (a_a(1) / a_o(1))) * a_o(0) * C_o(w,0)

a_a(1) / a_o(1) = (1 - (C_o(w,1) - C_o(b,1)) / (a_o(0) * (C_o(w,0) - C_o(b,0))))
C_a(1) = [C_o(b,1) - (1 - (a_a(1) / a_o(1))) * a_o(0) * C_o(b,0)] / (a_a(1) / a_o(1))

c_o(1) = C_o(b,1) - (1 - (a_a(1) / a_o(1))) * a_o(0) * C_o(b,0)
a_a(1) = c_o(1) / C_a(1) = a_a(1) / a_o(1)
a_o(1) = 1

===

a_o(0) := 1
C_o(b,0) := 0
C_o(w,0) := 1

a_a(n) = 1 - (C_o(w,n) - C_o(b,n)) / (C_o(w,n-1) - C_o(b,n-1))
c_o(n) = C_o(b,n) - (1 - a_a(n)) * C_o(b,n-1)
```

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
