### ISSUE TITLE
mirv_pgl doesnt send right version

### ISSUE THREAD

**Issue by FlowingSPDG** [advancedfx/advancedfx#184]
https://github.com/advancedfx/advancedfx/blob/5a0a0198cbd82ca829c2ee12e9ac706a477fe78e/AfxHookSource/MirvPgl.cpp#L66

it sends "2" even I enter ``mirv_pgl start 3``.

**Comment by dtugend** [comment]
Hi.

Only the description in
https://github.com/advancedfx/advancedfx/blob/5a0a0198cbd82ca829c2ee12e9ac706a477fe78e/AfxHookSource/MirvPgl.cpp#L1768
is wrong:

Sending version 2 is intended, since I made a "last minute" change in order to maintain backwards compatibility.

Edit: basically it behaves like the old version, unless the server.js use the new protocol commands (transBegin / transEnd) or events are enabled.

**Comment by FlowingSPDG** [comment]
I see,thanks for reply! then its not bug :D
keep it up!

**Comment by dtugend** [comment]
Sorry for reopening this, but the description being wrong still is a bug.

**Comment by FlowingSPDG** [comment]
thank you! :)
