### ISSUE TITLE
csgo crashes after executing pov cfg (latest version)

### ISSUE THREAD

**Issue by T4LC** [advancedfx/advancedfx#190]
This was a previous issue (#167) and it was stated to have been fixed, however for some reason the issue has risen again. I've narrowed down the crash to the command

mirv_cam source calcVecAng awmOfs ;

Whenever this command is run (with the other part of "pov.cfg") the game always crashes. This is the only command in the entire group that causes a crahsh.
Pov.cfg: https://pastebin.com/e8dvt1gn

**Comment by dtugend** [comment]
I can not reproduce the issue with the latest HLAE and CS:GO version:

## 1. Make sure you load with correct AfxHookSource.dll

We recommend using File -> Launch CS:GO instead of Custom Loader, because Custom Loader tends to start in old HLAE installs and thus people select an old AfxHookSource.dll there often.

If you are unsure, you can check / provide us with the AfxHookSource version by scrolling up the console after the game has been loaded, it should look something like this:
```
|
| AfxHookSource ([....])
| http://advancedfx.org/
|
| VClient: VClient018 (CS:GO)
| VEngineClient: VEngineClient014 (CS:GO)
| VEngineCvar: VEngineCvar007 (CS:GO)
| GameDirectory: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo
|
```

## 2. Make sure you are launching correct and fully-updated latest CS:GO install

Some people end up with two CS:GO installs and often enough launch the older (not updated one):

Please compare the **_full_** path to csgo.exe you set in HLAE with the one when you right click CS:GO in Steam Library -> Local Files tab -> Browse Local Files button.

Also enter version into your game's console, it should be like this currently (latest CS:GO update):
```
] version 
Protocol version 13701 [934/934]
Exe version 1.37.0.1 (csgo)
Exe build: 09:40:07 May 29 2019 (7508) (730)
Windows version [....]
```

**Comment by T4LC** [comment]
I've made sure that I am using the correct AfxHookSource.dll and the latest CS:GO install by looking through the console. I've already been using the File -> Launch CS:GO method to launch the game, but the issue is still there. I've also deleted all previous versions of hlae.

**Comment by T4LC** [comment]
Ok for some reason the issue has resolved itself, as I was testing trying out multiple different scenarios after doing a bit with mirv_campath and making a couple smooths the command seems to be working again, I don't know if this is the cause of it but everytime I restart the game it seems to be working fine now. thanks for the help!

**Comment by dtugend** [comment]
Consider verifying game cache (button on local files tab in properties dialogue of the game in Steam library).
