### ISSUE TITLE
Engine error how can i fix it?

### ISSUE THREAD

**Issue by cELTEXY** [advancedfx/advancedfx#211]
So when i launch csgo from HLAE and when i go to downloads to watch them, it downloads then it either crash or says that its and engine error. What should i do? Screenshot how the error looks like - https://gyazo.com/206ce48948d7c3091be29e5deff08218

**Comment by dtugend** [comment]
Which HLAE version are you using?
Can you enter version into CSGO console and copy and paste the output here?
Are there any other error messages e.g. when launching CSGO from HLAE?

**Comment by cELTEXY** [comment]
Im using the newest one. Hmh i dont understand the 2nd question tho. There is no other errors except a crash sometimes.

**Comment by dtugend** [comment]
Start CS:GO, open the CS:GO console, enter `version` and hit ENTER key / submit, then it should print the CS:GO version information in the console. Please copy & paste it here or take a screenshot.

**Comment by cELTEXY** [comment]
Protocol version 13708 [953/953]
Exe version 1.37.0.8 (csgo)
Exe build: 13:29:32 Jul 25 2019 (7508) (730)
Windows version 6.2 
----------------------------------
DONE

**Comment by dtugend** [comment]
Was the game loaded from HLAE when you did that? If not please repeat it from HLAE and check if it's the same or different.
(I am asking this, because some people have multiple CS:GO installs and accidentally select the older one in HLAE.)

Are you using custom loader or file -> Launch CS:GO?
If yes, might be worth check the AfxHookSource.dll that gets injected, you can do that by scrolling the console up to the beginning after launching the game form HLAE, it should look like this:
|
| AfxHookSource [....]
| [....]
|
(I am asking this, because it's very easy to accidentally select older DLL there if you have multiple HLAE installs.)

Also might be worth to verify game cache: Right click CS:GO in Steam Library -> Properties -> Local Files tab -> Verify Game Chache button. Let it verify and re-download a few files if required.

Is it only a specific demo or all demos?
Does it happen without HLAE too on that demo or not?

Please report back with the results.

**Comment by cELTEXY** [comment]
No it wasnt from HLAE, here is from HLAE - https://gyazo.com/4f76835120b6e7d309bb968ef787d205
It shows me this when i scroll up to the console - https://gyazo.com/e7e5a485f157df0176cdea5259e17a33
 And idk if it happens with other demos cuz i havent tried before.

**Comment by dtugend** [comment]
Thank you, sadly I don't see any obvious problems on those screenshots.

If it's only easily reproducible with that particular demo, would be cool if you can check if it happens without HLAE and if it only happens wit HLAE, please send us a copy of the demo (e.g. with services like https://send.firefox.com/), so I can try to reproduce the issue on my end.

**Comment by cELTEXY** [comment]
Okey, sad! ;(

**Comment by dtugend** [comment]
If it happens on all demos, let us know too please, also don't forget to verify game cache.

**Comment by dtugend** [comment]
Also if you used any others addons / DLLs besides HLAE, don't forget to check if it happens without those, (temporarily rename addons folder in C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo).

**Comment by dtugend** [comment]
Also try File -> Launch CS:GO dialogue in HLAE, tick mmcfg feature option and set an empty folder with the "browse" button for that option. If it doesn't happen then, we could use a copy of your config you use with HLAE, since it might be related to that.

Also if you use mirv_cvar_unhide_all in your moviemaking config:
You might be using a hidden CS:GO command to change a hidden setting that causes the crash in the end, had a person earlier with that problem.

**Comment by cELTEXY** [comment]
U can close it, i fixed it. I just deleted the CFG folder.

**Comment by dtugend** [comment]
now we will never know, what really caused it :(
Thanks nevertheless for reporting back though.
