### ISSUE TITLE
Dust 2 skybox

### ISSUE THREAD

**Issue by svetjana** [advancedfx/advancedfx#22]
how do i change it?

**Comment by dtugend** [comment]
# (HLAE, without mirv_streams)
```
mirv_cvar_unhide_all
mat_suppress "models/props/de_dust/hr_dust/dust_skybox/sky_dust2"
sv_skyname <skyName>
```

## To hide clouds as well:

```
mat_suppress "models/props/de_nuke/hr_nuke/nuke_skydome_001/nuke_clouds_002"
```

# (HLAE + mirv_streams)

Replace `<streamName>` with a name of your choice that's not used yet.

```
mirv_streams add baseFx <streamName>
mirv_streams edit <streamName> actionFilter add "models/props/de_dust/hr_dust/dust_skybox/sky_dust2" noDraw
mirv_streams preview <streamName>
sv_skyname <skyName>
```

## To hide clouds as well:
```
mirv_streams edit <streamName> actionFilter add "models/props/de_nuke/hr_nuke/nuke_skydome_001/nuke_clouds_002" noDraw
```

# Related:

You should somewhen watch this tutorial in my opinion:
[Tutorial: mirv_streams - picker - Hiding materials / entites and special effects
![Image](http://img.youtube.com/vi/aLxHUIOpGcU/default.jpg)
https://youtu.be/aLxHUIOpGcU](https://youtu.be/aLxHUIOpGcU)

The problem is that the sky dome used on dust2 looks very similar to the sky behind, meaning with mirv_streams picker you won't notice much of a difference whether it's not drawn / drawn, which results that it's hard to find in picker (you might give the picker a "wrong" answer due to that).

If you knew that problem, you could have made skyBoxTexturesAction temporarily "mask" (green), so that you can detect it more easily, that way we could have found that the material path / name is "models/props/de_dust/hr_dust/dust_skybox/sky_dust2".

## Related Links:
[HLAE forum - Replace sky with mirv_streams on nuke / inferno / train](http://advancedfx.style-productions.net/forum/viewtopic.php?f=17&t=2055)

**Comment by svetjana** [comment]
Ty man. I knew it was something "models/props...." but it wasnt hrnuke etc like in inferno or train. but ty :)
