### ISSUE TITLE
Campath time smoother™

### ISSUE THREAD

**Issue by z8editing** [advancedfx/advancedfx#223]
I have a feature request that would help alot when using campaths.
Let's say you place four keys with great camera angles but the demo has to be played with a low timescale to get a specific shot.
Most of the time, one of these four keys will have a significant time difference between the n-1 and n+1 key, causing the campath to abruptly stop or going to a different direction. One 'simple' fix for us movie makers, is to re-make the campath trying to separate the keys nicely in time to have a better interpolation.
So my request is this: is it possible to enter a command that would not necessarily make the keys at even time difference, but at least smooth that difference ?
Its basically a matter of moving the keys in time.
That's my idea. No idea if it's possible to achieve but it would be a huge help.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
