### ISSUE TITLE
Publish advancedfx as addon artifact

### ISSUE THREAD

**Issue by thiagofelix** [advancedfx/advancedfx#24]
Is it possible to build advancedfx as a addon library independent of HLAE executable?

My intention is to run commands like `mirv_deathmsg` without having to load csgo using HLAE executable.

I was thinking in spend some time creating a build script that compile the csgo commands into a standalone DLL artifact which we can use independently from HLAE.

Please let me know if this approach makes sense.

Tks

**Comment by dtugend** [comment]
If you mean an addon plug-in for CS:GO like [https://github.com/saul/csgo-cvar-unhide](https://github.com/saul/csgo-cvar-unhide):
This would limit HLAE's features, since the plug-ins are loaded relatively late: For example mirv_streams and other HLAE features require to hook the Direct3D9 interface the game sees in order to operate properly - these hooks would not work with such a plug-in DLL, because it simply happens too late: The plugins are loaded after the relevant calls to Direct3DCreate9.

In case you didn't know, HLAE has a no-GUI mode: https://github.com/ripieces/advancedfx/wiki/HLAE-Interfaces#command-line-parameters

**Comment by thiagofelix** [comment]
@ripieces Yeah that is the use case I meant. I am aware of the no-GUI mode and use it quite a lot. I appreciate you explaining about the `mirv_stream`. 

I am looking for using `mirv_deathmsg` in a cross-platform environment hence my suggestion to publish as plugin, either that or compile HLAE for cross platform would work too (maybe create a make build?). 

How about extracting `mirv_deathmsg` commands as separated library/plugin that can be used standalone or bundled inside HLAE? I will keep digging the code to understand how feasible is that

**Comment by dtugend** [comment]
HLAE (and it's predecessor MIRV Demo Tool) has always been for Windows only so far. You will run into severe problems if you want that to be cross platform, because many essential hooks (i.e. for mirv_deathmsg) are binary hooks, since there are no interfaces exposed by the game you could hook for these. (The binaries of Windows / Linux / Mac are very different of course.)

**Comment by thiagofelix** [comment]
Oh I see. Didn't know about the binary hook to expose deathmsg, I thought it was exposed by hl2sdk, so that makes sense not be possible to port to other platforms, thanks for letting me know and preventing me to waste time in wrong direction.

**Comment by dtugend** [comment]
Well it is possible to port them, but it needs adjustments for every platform aka not trivial. I am closing the issue, if you want it to be reopened, just mention it.
