### ISSUE TITLE
2.82.0 contains trojan: Win32.Startun

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#250]
I'm using CSGO DemoManager wich uses HLAE - usually after CS update demomanager downloads new version of HLAE if available - but as no info popped up I downloaded latest installer manual - my antivirus denied it with message: infected with Win32.Startun ... thx for spamming malware around the net ...

**Comment by dtugend** [comment]
Have you considered it might be a false positive?
We had to suffer from several false-positives in the past.

It might be helpful to know your Anti-Virus. (If it's not e.g. Sophos, then we might be able to contact and check with them.)

If you are using Windows Defender, make sure the definitions are fully updated (if not updated them **and reboot**): https://www.microsoft.com/en-us/wdsi/defenderupdates

**Comment by ghost** [comment]
wouldnt call this a false positive:
https://www.virustotal.com/gui/file/2bcb514b75a16a20b063be2c2a03f4cda2b0f9e8e2032f14817da39207c52d1b/detection

**Comment by dtugend** [comment]
I am contacting some of the AV vendors for further info, to see what the issue is and if it can be resolved.

**I'd like to note, that for example Windows Defender (Microsoft) is listed there, but the files goes through just fine with the latest definitions here.**

I can not do much about Sophos AV, those have been very unhelpful in the past.

Also already had the situation in the past were Virus AV vendor said I must contact VirusTotal to resolve the issue and VirusTotal said I must contact the vendor.

Things are not as easy as they may seem.

I can assure you I did not intentionally (also probably not unintentionally) put any Virus / PUP / Adware / Trojan inside, however during execution the installer will download latest FFMPEG from https://ffmpeg.zeranoe.com/builds/ which might be what is triggering some AV.

But let's wait if and what the vendors I contacted will say.

**Comment by ghost** [comment]
i neither dont know nor give a damn why keep mention defender in specific - i never used it and never will and anyone rely on what win10 brings along with basic security is either just lazy or don't give a damn about it's security
also as the internet doesn't give any explain what trojan.startun is or what it does it could be anything or nothing

**Comment by xNWP** [comment]
We understand that seeing a scary message like "Trojan.Startun" can be concerning. However as this is technically a "cheat" program, it does perform various code routines that some antivirus software can falsely identify as malicious activity. We understand that not everybody however is computer literate and can identify a false positive given the context, however we do expect the average user to recognise this given the fact that the software is used by many professionals, and businesses. If this however is not enough to convince you, that is completely fine, simply do not use the software. However this is a GitHub issues page, it's purpose is to help advance and identify bugs in the software, this is not the place for you to vent your computer illiteracy.

Furthermore, the language you've chosen to adopt is inherently hostile and in direct breach of GitHub's terms of service, which you may verify yourself here: [https://help.github.com/en/github/site-policy/github-terms-of-service](https://help.github.com/en/github/site-policy/github-terms-of-service) (Sub-section community guidelines).

If you have any concerns related to the development of the software, feel free to open another issue, however I will be closing this one as it is not a valid use of the GitHub issues page. Harassment of any kind will not be tolerated towards any maintainers, users, or any other persons involved in the context of the HLAE software.

**Comment by dtugend** [comment]
While I agree with xNWP being less hostile is a good idea, I do have to reopen the issue, since it's not solved to a satisfying degree yet and other people might have similar questions.

As you can see on Virustotal two vendors already updated their definitions, even though only Kaspersky replied so far of those two I contacted (hopefully trend micro will reply next week).

Edit: You need to understand though that there many AV vendors that even share definitions (including false positives) with each other directly or indirectly, so clearing false-positives takes a lot of time and resources for us and sometimes is not worth it.

**Comment by ghost** [comment]
what the hell do I care if someone feels threatened by just misunderstanding me? it's always what you undestand - not what I say
if you think that "I don't give a F" is a personal insult or threat - be my guest - Darwin's next door
if you think that it's against any policy - use report function so an official of the used service can review it and will decide - if you try to threaten me by lines like "hey bud, that's against the 'rules'" - sorry, but it's not for you to judge about this - if you want to play that game - I'm really good at it
also: a false positive malware report in fact really is a bug as it's on you, the dev, to figure out why your code pops up as matching malicious signatures
simple example: it's easy to write a small three-line code in java to wipe your complete harddrive and no antivirus in the world will ever detect it as simple file traversal and calling the delete method on each file is legit code - that someone can build something harmful with it - no doubt about that - but when using a language compiled into machine code contain low-level assembler lines - just try to excuse "yea, it's baiscally a cheat program" - c'mon - at least TRY to come up with something believeable
most hackers use hooking of the render methods - and in my long career I only had one or two injectors ever detected that hooking another process might be a dangerous action - so, the chances are pretty high that something here doesn't match up - this is back by clone and build the repo myself didn't trigger my AV - so, as I can't reproduce the binary myself from the provided source makes it at least an option that the provided binary isn'T build from the source provided

about don'T use it: well, I used it as part of csgo demo manager - but if I look back how many cheaters I encountered just over three months - I don't play it anymore and hence not using csgodm - so I DON'T CARE - keep spreading malicious code and try to hide it as false positive ...

**Comment by Devostated** [comment]
Hello cryptearth,
our tool HLAE is completely open source. Feel free to check every single line of code and compile the program yourself. 

Best regards,

Devostated

**Comment by xNWP** [comment]
Again, this is not the purpose of the GitHub issues page, please try to keep talk on topic. Accusing the developer(s) of this software of spreading malicious code (an illegal activity in most countries) is a form of harassment and is against GitHub's ToS.

To address some of your concerns/claims:

> if you try to threaten me by lines like "hey bud, that's against the 'rules'

That is not a threat and was not intended as one, a threat implies hostile action of some kind.

> if you want to play that game - I'm really good at it

That is a threat and again will not be tolerated.

> a false positive malware report in fact really is a bug as it's on you, the dev, to figure out why your code pops up as matching malicious signatures

While we do try to avoid these issues all together, they are inevitable. HLAE works by attaching to the game process and then injecting code into it. This is inherently suspicious to any anti virus software and there is simply no other way to do this. We mitigate this issue by keeping in touch with anti virus companies and having them review their flags as they pop up. @dtugend has already been hard at work, and as he said 2 of the false positives have already been reviewed and removed. If you believe the folks at Kaspersky are also lying about this to help us put malicious software on user machines (while risking their career and integrity)... you will need to talk to them.

> it's easy to write a small three-line code in java to wipe your complete harddrive and no antivirus in the world will ever detect it as simple file traversal and calling the delete method on each file is legit code

This is a blanket statement, whether or not an antivirus will pick up on a file like this is down to the implementation of the antivirus software. While java does use an interpreter, the instructions can still be analysed like any other binary file, and patterns can be found depending on the heuristic model of the antivirus software.

> but when using a language compiled into machine code contain low-level assembler lines

For starters... Assembly is a programming language, just like C, just like C++, just like Java, just like Python. So to say a language compiles to low-level assembly doesn't really make sense in this context. Also while it is true that compiled languages compile to binaries containing pure machine code, all programs at some point in their execution are converted to machine code. A CPU simply cannot understand anything other than machine code.

> and in my long career I only had one or two injectors ever detected that hooking another process might be a dangerous action 

This action alone is one of the biggest red flags for any antivirus, our injector has been detected multiple times and has been reviewed and cleared by most antivirus companies in each instance. I can't speak to your "long career" of experience, but in my professional experience this is not the case whatsoever.

> this is back by clone and build the repo myself didn't trigger my AV - so, as I can't reproduce the binary myself from the provided source makes it at least an option that the provided binary isn'T build from the source provided

This claim is bizarre for sure, I can't really say for sure why only the official release is getting triggered for you, but since you've gone ahead and built the binaries, can you go ahead and post some screen shots of your completed built, along with some form of checksum to verify?

> keep spreading malicious code and try to hide it as false positive

We don't, we haven't, and we never will.

I understand that you're suspicious of us, a healthy suspicion is always a good thing. However, if you do in fact think we're untrustworthy, then you should report us to GitHub, not come here and attack us. Because if you're wrong, then that's simply harassment.

Also providing us with run on sentences of theories is not really helpful to anyone here and only proves your computer illiteracy. I'm glad that you're interested in computers and these kinds of things, however, your internet degree does not replace my 4 year degree in Computer Science. We are not looking to argue, we are looking to develop software for the esports and content creation industry. If you have any questions or concerns pertaining to that we would be happy to address them, however we will not be wasting any further time addressing baseless accusations that only aim to defame and harass the maintainers of this project.
