### ISSUE TITLE
fov_cs_debug (weird scope)

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#272]
**when i change fov scope looks weird** 
i used to change fov without any problem
any command to fix this ???

**Comment by dtugend** [comment]
## Preparation:
```
fov_cs_debug 0 // default
mirv_fov handleZoom enabled 1
```

## Set engine FOV to 110
```
mirv_fov 110
```
which can be different due to aspect ratio scaling if your aspect ratio is not 4:3

## Or Set real FOV to 110
```
mirv_fov real 110
```

## Restore default FOV
```
mirv_fov default // restore default fov
```

Releated reading:
- https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_fov
- https://github.com/advancedfx/advancedfx/wiki/CS%3AGO-Calculate-real-FOV-from-engine-FOV---mirv_fov
- https://github.com/advancedfx/advancedfx/wiki/Source%3ACommands
