### ISSUE TITLE
Changing color of matteEntity?

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#280]
Hello,
Is there any way to render a matteEnitity stream not with a green color? For example black or even maybe transparent.
Is there any workarounds I could use?
Thanks in advance!

**Comment by dtugend** [comment]
Use `mirv_streams edit <streamName>` and change all actions that are `mask` to `black` or `nodraw`.
If you want a wall-hack stream, please look at the `wh.cfg` that comes with HLAE instead, you can test it with `exec afx/wh.cfg`.

**Comment by dtugend** [comment]
If you need another color than black / white / mask (green), then look at the .vmt files with the same name that come with HLAE on how to do it and look ad wh.cfg that comes with HLAE on how to load own materials.

**Comment by ghost** [comment]
> 
> 
> and change all actions that are `mask` to `black`

That worked. Thanks!

**Comment by ghost** [comment]
Hello once again,
I just found out about the "matte" stream. It is perfect for my needs with almost 0 modifications, but it seems that I can only use drawMatte with that stream, because with "draw" it is not actually drawing anything.
Is it possible to somehow use "draw", since I am changing in-game models with self written program  and they don't render with "drawMatte"?

**Comment by dtugend** [comment]
Fore the "matte" stream there's two actions: drawMatte and noDrawMatte.

The stream operates as follows:

1) Check if an object resolves to drawMatte action, if yes it is drawn, otherwise continue with 2).
2) Check if an object resolves to noDrawMatte action, if yes the object is not drawn, otherwise continue with 3).
3) The "matte" stream is resolved from two streams/renderpasses: Objects that reach 3) are drawn black on the first/0/entBlackBg pass and white on the second/1/entWhiteBg pass.

So if your object is not drawn, despite of noDrawMatte action it can have these reasons:
1) it's not in drawMatte action
2) it's in noDrawMatte action
3) it's overDrawn by another object that makes it into Step 3) from the previous paragraph.

Since you are using a self-made program to change models, be aware that HLAE's current detection of stream properties is mostly material based.
The easiest way to make your objects draw in the matte is knowing their material name(s) and list those in the actionFilter as drawMatte, because the actionFilter wins before all other stream properties. Related Tutorials: https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams---picker---hiding-materials--entites-and-special-effects
I recommend the longer one if it's not to annoying, because it explains the actionFilter. You might also want to check out the actionFilter's addEx command (I think only add is explained) and the fact that add and some options of addEx support the wildcard `\*` (\\ = `\\`).

Please be aware that the matte stream is not officially supported I think. It will have problems especially with semi-transparent objects in-front or between your matte objects, smoke and also is not perfect.

**Comment by ghost** [comment]
Thanks again!
