### ISSUE TITLE
Linear campath?

### ISSUE THREAD

**Issue by GustaCz** [advancedfx/advancedfx#281]
How do I make campath go from point A to point B linearly without it doing a circle for whatever reason?
https://i.imgur.com/w3BBtGk.jpg

**Comment by dtugend** [comment]
You could switch the path to linear interpolation, but that will make the whole path very unsmooth not only the segment between A and B, which is not what you want.

Until we provide segment-wise options, the recommended method is to dampen the effect, by pausing the path in the middle of time between A and B and then moving the camera to the middle of the segment between A and B.

(The reason for this behaviour is that it tries to pass the keyframes at the exact time and position you set and that some keyframes later on affect the solution / path it takes as well, since it tries to be C2 smooth for position and quaternion rotation.)

**Comment by dtugend** [comment]
I meant you basically add another keyframe there in-between A and B.

**Comment by GustaCz** [comment]
Oh why didn't I think of that?

Anyway, thanks and keep up the good work
