### ISSUE TITLE
Questions regarding sampling system example usage

### ISSUE THREAD

**Issue by robbyjm** [advancedfx/advancedfx#284]
I have a few questions regarding the following code snippet found on this page in the wiki that I was hoping to get some clarification on. https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams

1. What does `mirv_streams settings edit afxSampler30 settings afxClassic` do? It looks like we are editing the `afxSampler30` to have the same settings as `afxClassic`. If this is the case, what are the `afxClassic` settings?

2. Why are we doing what looks like the opposite of the first line here? `mirv_streams settings edit afxDefault settings afxSampler30`

3. are we recording at 1200fps or is this 1200sps?

```
mirv_streams settings edit afxSampler30 settings afxClassic // if you have FFMPEG installed for HLAE, you can use one of those settings (e.g. afxFfmpegYuv420p) instead of afxClassic
mirv_streams settings edit afxDefault settings afxSampler30
mirv_streams add normal myNorm

// Start recording:
host_framerate 1200; mirv_streams record start

// End recording:
mirv_streams record end; host_framerate 0

```

**Comment by dtugend** [comment]
1. It sets the output of the afxSampler settings to be connected to the afxClassic settings (usually TGA image sequence in default or BMP, depends on the mirv_streams record settings). You could connect them to something else, e.g. FFMPEG settings.
2. This tells the default settings that they shall output to the sampler instead of what they were connected before (afxClassic). Basically it says "by default I want my streams to use the sampler".
3.  host_framerate is the Samples Per Second (1200 in your example). The FPS is the output framerate of the sampler, which for afxSampler30 is 30. You can add an own sampler and edit the output FPS to be different (e.g. 60).

**Comment by robbyjm** [comment]
as always @dtugend thank you for your response!
