### ISSUE TITLE
Cannot start HLAE

### ISSUE THREAD

**Issue by xDries** [advancedfx/advancedfx#29]
I cannot open hlae 
When i try to start it up my csgo.exe deletes and hlae gives some errors can someone help me please
I use HLAE 2.44.0

**Comment by dtugend** [comment]
This is most likely caused by your Anti-Virus.

To be honest an anti-virus that deletes csgo.exe because it is accessed by an process (injector.exe) that it detects as dangerous is shitty.

Try to add an exception to it for HLAE.exe, the injector.exe (32 bit) in the HLAE.exe folder (the one in x64 sub-folder doesn't matter, it's for 64 bit).

If it's like the problem one guy had, it will keep deleting csgo.exe, even if those are whitlisted. In that case try to add an exception for csgo.exe as well (even though that's logically pointless, because HLAE / it's injector does not modify it at all).

If that still doesn't work, I strongly recommend to try another Anti-Virus.

**Comment by dtugend** [comment]
Due to lacking feedback I am closing this issue as solved.
In case it's not solved, please provide further feedback.
