### ISSUE TITLE
Engine Error - Too many verts for a dynamic vertex buffer (43688>32768)

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#294]
From https://hlae.site/topic/147/

He was using my ffmpeg.cfg p0 preset

Game crashed when recording

**Comment by dtugend** [comment]
The FFMPEG cfg alone should not be able to cause this.

Most likely he is using afx/wh.cfg or a similar cfg combined with a non-default (other than -1) r_farz value.
You have to make sure r_farz remains -1 ( -1 means to use the value in env_fog_controller), otherwise the game can crash, because it puts too much stuff onto the drawing queue, more than it can handle. It could even crash without HLAE then.

If that doesn't solve the issue, we need the demo, demo time (and recording position / campath except if it's POV) and the exact configuration used in order to reproduce the issue.

**Comment by dtugend** [comment]
Please reopen when further information is available.
