### ISSUE TITLE
AfxHookSource

### ISSUE THREAD

**Issue by slimbit** [advancedfx/advancedfx#297]
when running CS:GO via Hlae, an error appears, and instead of new models ERROR, please help))))((((
![Screenshot_2](https://user-images.githubusercontent.com/62498819/77245625-20175080-6c4a-11ea-8b6f-27eb84d9663d.png)

**Comment by dtugend** [comment]
You probably have two CS:GO installs and are launching the older one.

To solve this you need to find the right _full_ path to the newer csgo.exe.

1. Right click CS:GO in Steam Library
2. Properties
3. Local Files tab
4. Browse Local Files button
5. Click in the top bar where it shows the shortened path in order to get the fullpath.

Use that and add `\csgo.exe` to it, so e.g. mine / the most common path is this one:
`C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`
