### ISSUE TITLE
Can't launch demos

### ISSUE THREAD

**Issue by ShreKyy** [advancedfx/advancedfx#298]
When I launch into CSGO there is a yellow bar on top saying "Steam Client Needs to Update".
I have the steam client updated,it only shows up when I launch the game via HLAE,but if I launch it normally,its all good.I have the ProgramPath and the hook dll files correctly selected in the Custom Loader.
Please help me solve this problem.

**Comment by ShreKyy** [comment]
Forgot to mention that when I try do load demos,it loads like halfway through and then redirects me back to the dashboard.

**Comment by dtugend** [comment]
You probably have two CS:GO installs and are launching the older one.

To solve this you need to find the right _full_ path to the newer csgo.exe.

1. Right click CS:GO in Steam Library
2. Properties
3. Local Files tab
4. Browse Local Files button
5. Click in the top bar where it shows the shortened path in order to get the fullpath.

Use that and add `\csgo.exe` to it, so e.g. mine / the most common path is this one:
`C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`

**Comment by ShreKyy** [comment]
Turned out this was the problem,since I have a new pc i accidentally installed the game twice and put the wrong path in.
Thank you a lot for the quick response.
