### ISSUE TITLE
HLAE Starting UP on Guest-Permitted Accounts (Windows)

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#3]
I was using an old HLAE version a few months ago, which allowed me to run it without a admin rights, but with the latest update, I am unable to? Is it possible to fix this in the next update or no?

**Comment by dtugend** [comment]
There has nothing changed related to that, please tell me the error message you get or what happens!
You should be able to run HLAE 2.30.**4** without admin rights. Make sure that csgo.exe and Steam.exe are set to be run without admin rights too, otherwise HLAE can't access them.

**Comment by ghost** [comment]
It says "Windows protected your PC, Windows Smartscreen prevented an unrecognized app from starting." Then if I want to run it, I need a password.

**Comment by dtugend** [comment]
I cannot do much about Windows SmartScreen to be honest:
The only option would be to code sign the HLAE.exe and so on, which I am not planing to do, because the certificate required for that costs a considerable amount of money, which I am not willing to spend.

Your options are:
1) Wait until enough users have run that HLAE version and SmartScreen considers it known or s.th..
2) Use another Windows account to Unblock the .exe files (HLAE.exe, injector.exe x64\injector.exe) in the HLAE folder: https://www.google.com/search?q=windows+smartscreen+file+properties+unblock&tbm=isch

**Comment by dtugend** [comment]
Closing, I tried to give some possible options for working around the problem, without code signing there is not much I can do.
