### ISSUE TITLE
CS:GO Steam overlay screenshot (F12) does not work anymore when game is not launched from official Steam Library entry (CS:GO 2020-03-26 pre-release / silent update)

### ISSUE THREAD

**Issue by OraCheung** [advancedfx/advancedfx#301]
(Please search exiting **open and closed** issues first to verify this is a new bug report.)
In old version game, -panorama -afxDetourPanorama can change the UI and use the screenshot function provided by steam(usually by pressing the f12 button) . But after game update 2020-03-26, it is invalid after using 
-afxDetourPanorama to start the csgo client.

**Comment by dtugend** [comment]
0) The update you are referring to is a pre-release, not an official CS:GO release.
1) Did you update your modified panorama files with the latest ones? If not please do so.
2) Did you test if it happens without HLAE? I am asking because- afxDetourPanorama is not related to the screenshot function. If it happens without as well you might want to report that bug to the Valve CS:GO devs instead.

Edit: Also there was a Steam client update, which might have more impact.

**Comment by dtugend** [comment]
This problem is caused when using HLAE in general, it's not related to afxDetourPanorama

**Comment by OraCheung** [comment]
I open csgo directly (not using hale) screenshot is ok.
So, are there plans to fix this?

**Comment by dtugend** [comment]
If possible please use the "screenshot" console command as workaround for now:
`bind <key> screenshot`.

**Comment by OraCheung** [comment]
I try in the game.But it do not work.
I first open the console, and then input
`bind F2 screenshot`
But when I press F2, nothing happen

**Comment by dtugend** [comment]
the screenshots are stored in csgo folder:
C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\screenshots

**Comment by dtugend** [comment]
I found the reason, update will be released soon:
`SteamOverlayGameId=730` is required in evironment variables for CS:GO to work now.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.91.3.1
