### ISSUE TITLE
..\shared\econ\econ_item_system.cpp line 272 assertion failed

### ISSUE THREAD

**Issue by oaxzy** [advancedfx/advancedfx#305]
I'm trying to record some clips and cines for a csgo edit I'm working on, but when I launch csgo through either the default csgo launch or a custom loader, this message pops up. Csgo opens up as just a black screen in the background. I've tried reinstalling both csgo and the new version of HLAE, but nothing seems to work. What should I do?

![assertionfailed](https://user-images.githubusercontent.com/62845618/77853932-ada7f280-71ac-11ea-874a-81197689d5ef.JPG)

**Comment by dtugend** [comment]
You might have two CS:GO installs and are launching the older one.

To solve this you need to find the right _full_ path to the newer csgo.exe.

1. Right click CS:GO in Steam Library
2. Properties
3. Local Files tab
4. Browse Local Files button
5. Click in the top bar where it shows the shortened path in order to get the fullpath.

Use that and add `\csgo.exe` to it, so e.g. mine / the most common path is this one:
`C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`

----

Please compare the full-paths thoroughly, had two cases lately were people said it would be the same while it wasn't.

Please report back whether or not this solved your problem.

If it didn't solve your problem, please provide:
- the settings you tried in the File -> Launch CS:GO dialogue.
- the output when you enter `version` into the game console
- other info that might be useful for investigating the problem (please do not provide personal data)

(Please note we only support the official Steam CS:GO version.)

**Comment by oaxzy** [comment]
Thank you so much, this ended up working for me. I've had this problem for the longest time, and you just fixed it! Thank you.

**Comment by soraxde** [comment]
Yooo, I had the same problem yesterday. Those steps didnt work for me, but I could solve the issue. You can let steam check the game in the local files tab :). So it will search for issues.
