### ISSUE TITLE
i can't change graphic settings

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#309]
after recording with HLAE.....
i changed settings to low but graphic still high
is that because i used HLAE !?

**Comment by dtugend** [comment]
1) HLAE does not actively change your settings.
2) We recommend enabling and using the movie making config folder (mmcfg folder) feature in File -> Launch CS:GO to prevent demos + yourself from changing your gaming settings while being launched from HLAE.
3) If it shows low in the video settings and seems high, this is a known problem since the latest CS:GO updates and not realted to HLAE: https://www.reddit.com/r/GlobalOffensive/comments/8d97p1/shaders_forced_to_high_since_last_update/
4) If the game resets to high after you changing it too low and also displays so in graphic settings, then you probably overwrote and or write protected your gaming config.
