### ISSUE TITLE
How to make the camera stay in the position where the animation ends?

### ISSUE THREAD

**Issue by lawchak** [advancedfx/advancedfx#313]
(Please search exiting **open and closed** issues first to verify this is a new question.)

**Comment by dtugend** [comment]
For GOTV demos currently you can only use this workaround:
- note down position from `spec_pos`
- go to that position with `spec_goto` after starting the animation
- recommended to use `cl_obs_interp_enable 0` with that

The reason it works for servers is that HLAE uses additionaly a code path to request moving the player on the server there, in order to avoid / dampen problems with the server-side visibility checks, this code path will not work on GOTV demos however.

**Comment by Dechno1337** [comment]
GUI idea (for the campath section): Add a toggle / checkbox that lets you choose whether you want the camera to stay where the campath ends or not. :)

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.138.1
