### ISSUE TITLE
Multi-stream recording with ffmpeg cause game crashes

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#314]
Settings&Scripts:
https://github.com/Purple-CSGO/CSGO-Config-Presets/blob/master/ffmpeg.cfg
https://github.com/Purple-CSGO/CSGO-Config-Presets/blob/master/stream.cfg

commands input & keys pressed:
exec ffmpeg
prores
exec stream
[F1] [Ins]
[F2] [Ins]
[F3] [Ins]
[F4] [Ins]
[F5] [Ins]
[F6] [Ins]
host_framerate 300
mirv_streams record start

Result:
Game crashes when clips are 5~6s long, once 10s long

**Comment by dtugend** [comment]
Hi, I recorded clips with your config with them being of 40+ seconds duration  at 720p without any crashes already and will record to 1+ minute to see if that changes anything.

1. Please check that you have enough hard disk space, I am not entirely sure how things will behave if it runs out of hard disk space.
2. Please check that nothing on your PC is overheating: CPU, RAM, (maybe also GPU).
3. If you overclocked your PC (especially) RAM, that can be the source of problems too.
4. Try if it lasts longer at lower resolutions (e.g. 720p).
5. It might be related to other features you are using or enabled, please try to narrow it down.
6. Make sure you are using latest HLAE, there's been some things changed / fixed with regards to streams just a few versions ago. Also make sure your CS:GO is fully updated.
7. A crash dump from of the crash can be helpful too, they are usually in Steam/dumps folder (.dmp) or side-by-side with csgo.exe (.mdmp). Please do not upload it publically, email me a link instead.
8. Also please provide more information about the nature of the crash (e.g. if game closes or freezes?).

**Comment by Purple-CSGO** [comment]
No crashes now
