### ISSUE TITLE
Auto updating

### ISSUE THREAD

**Issue by patchzyy** [advancedfx/advancedfx#321]
Would it be possible to have HLAE auto-update?
I would really love to see this feature added, I personally think that it would be a great addition.

**Comment by Dechno1337** [comment]
For the installer version it makes sense.

Not sure about the .zip version though. (?)

**Comment by dtugend** [comment]
real auto update without using a system service is not possible due to the installer requiring permissions
maybe I will just do update available, click here to download and install
like other programs like VLC and Notepad++ do

but not sure how that would be much better than now
where it leads directly to release page
ok less clicks and thinking maybe

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.

**Comment by Dechno1337** [comment]
Maybe Devo's tool is something to consider instead?
https://github.com/Devostated/HLAELauncher
