### ISSUE TITLE
How to only show the map in demo.

### ISSUE THREAD

**Issue by math4672** [advancedfx/advancedfx#327]
Hi!
My problem is that I would like to make ingame recordings of only the maps with hlae. 
I've used these commands to remove the players from my demo, but i can still see their shadows, blood and bullets.
mirv_streams add matteWorld wrld
mirv_streams preview wrld

Is there any way to completely remove all players and shadows, ext?
![shadows](https://user-images.githubusercontent.com/65218189/81653505-1f728d80-9435-11ea-874b-9371ab07448c.png)

Hope you can help :)

**Comment by dtugend** [comment]
If you only need maps and no other stream, might be easier time-wise to record an empty map with GOTV really and use that.

Otherwise: yes there is, but it's some work:

Here's two tutorials on how to use actionFilter:
https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams---picker---hiding-materials--entites-and-special-effects
The second one by me even explains the more advanced addEx option with shadows.
Be sure to make use of the WildCard feature (`\*`).

For blood removal you can save some time, someone already made a config here you can use:
https://twitter.com/MolenTV/status/1134400694335791105

**Comment by math4672** [comment]
Thank you so much for the help Dominik 😊

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Dominik Tugend <notifications@github.com>
Sendt: Tuesday, May 12, 2020 10:03:56 AM
Til: advancedfx/advancedfx <advancedfx@noreply.github.com>
Cc: math4672 <kammers-gaard@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [advancedfx/advancedfx] How to only show the map in demo. (#327)


If you only need maps and no other stream, might be easier time-wise to record an empty map with GOTV really and use that.

Otherwise: yes there is, but it's some work:

Here's two tutorials on how to use actionFilter:
https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams---picker---hiding-materials--entites-and-special-effects
The second one by me even explains the more advanced addEx option with shadows.
Be sure to make use of the WildCard feature (\*).

For blood removal you can save some time, someone already made a config here you can use:
https://twitter.com/MolenTV/status/1134400694335791105

**Comment by dtugend** [comment]
Be aware that the mirv_streams system is a bit broken currently (e.g. greenscreen won't work) due to latest CS:GO update and has yet to be fixed.

**Comment by dtugend** [comment]
It's been fixed in latest HLAE v2.94.2, closing since your question seems to be answered.
