### ISSUE TITLE
Error: name is already in use / Error: Cannot remove "name": Still in use.

### ISSUE THREAD

**Issue by BNEX** [advancedfx/advancedfx#33]
I have a question guys... I undesrtood how to use the mirv_calcs, but I'm trying to use again in other projects and I get a error:

"error name is already in use"

I trying this command: 
mirv_calcs handle remove "name"

example:
mirv_calcs handle remove "name"
Error: Cannot remove "name": Still in use.

How can I remove that correctly? Can someone help me?

**Comment by dtugend** [comment]
Most likely you have mirv_calcs in your movie making config, easiest solution would be to remove them and their usage in mirv_cam / mirv_aim from there.

Since mirv_calcs / their usage depend on each other, they need to be removed starting with those usages that have no further dependencies first, this means:
1) Remove them from being used in mirv_cam / mirv_aim first (mirv_cam source calcVecAngClear, mirv_aim calcVecAngClear).
2) Then continue removing those with no further dependencies from mirv_calcs first (i.e. in reverse order you created them).

Edit: HLAE doesn't manage the dependencies using a dependency graph, instead it manages them by reference counting (meaning it can't tell you the child dependencies of a calc directly, only it's parent dependencies). If you find any mistakes in the dependency managment (i.e. calc not being removeable that should be), then please let me know.

**Comment by BNEX** [comment]
I just needed to know for editing that camera for other players and project I'm making it... 
I'm trying a lot of things today, and alone in game I discover how do it. I just use this command:

mirv_calcs handle edit key key "number of player"

If this command helps somebody, there we are =)

By the way, thanks for reply ripieces, all information helps us ;)

**Comment by dtugend** [comment]
There are 1 or 2 tutorials on YouTube, search for mirv_calcs

If the issue is solved, please don't forget to close it :-)
If you have further questions, you can leave it open of course.
