### ISSUE TITLE
Faster Campath Editing

### ISSUE THREAD

**Issue by Twissen** [advancedfx/advancedfx#333]
I just saw this video. I loved the little info box for every action and I loved how he fastly modified his keyframes. In the description, he says "Some people compare this to HLAE. Please don't. HLAE is a much more advanced program." Indeed it is. But is it somehow possible to have that fast/flexible campath editing in the future?
[https://www.youtube.com/watch?v=NDczxKqJECY](url)

He also shares his script here:
[https://github.com/samisalreadytaken/keyframes](url)

**Comment by Dechno1337** [comment]
This is something the HLAE GUI should be able to do, eventually. But the GUI is only in the planning / designing phase as far as I know. :thinking: So might take a while.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
