### ISSUE TITLE
Demo's audio problem

### ISSUE THREAD

**Issue by Crolfhym** [advancedfx/advancedfx#337]
I found that whenever I slow down or fast forward the demo. The audio of game will not change its tune and speed. That makes me very annoy :(
I am using the latest HLAE version and I sware that my steam and CSGO version is up to date.

**Comment by Twissen** [comment]
I don't know if it's a new bug or not. I didn't test it yet. But the problem should be about timescale commands. Make sure "mirv_snd_timescale" is set to "1" and "host_timescale" is set to "0".

**Comment by Crolfhym** [comment]
Yea I just did as you said but it didn't work too.

**Comment by Dechno1337** [comment]
_mirv_snd_timescale 1_ will always play the sounds in normal speed / pitch, and it doesn't follow the demo speed, while _host_timescale 1_ does.

_mirv_snd_timescale 0.5_ will play the sounds in 50% slow motion for example.

**Comment by dtugend** [comment]
This is cause by mirv_snd_timescale and an intended feature in order to make HLAE work with host_timescale 0, which is required for smoother demo playback upon low FPS when recording HQ images / many streams.

If you don't need to use host_timescale 0, then please use `mirv_snd_timescale default` to restore the original game behavior (changing with demo speed).

**Comment by Crolfhym** [comment]
Thank you so much bro. My problem is solved when I use "mirv_snd_timescale default".
