### ISSUE TITLE
Can I use HLAE at GOTV LIVE server ?

### ISSUE THREAD

**Issue by soscaster** [advancedfx/advancedfx#343]
I want to use HLAE to make camera paths LIVE like things that ESL does on their spectator.
Can I use it and bind camera paths on each keys like "spec_lerpto" ?

**Comment by dtugend** [comment]
You can connect to the GOTV with official HLAE only if you have the IP using it's IP and the right GOTV port, otherwise no.
Camera paths can be saved and loaded and offset in time after loading etc, via console commands, so you can also bind them to a key:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_campath
