### ISSUE TITLE
[Bug] ffmpeg/readme.advancedfx.txt file does not exist in the installer

### ISSUE THREAD

**Issue by cherinyy** [advancedfx/advancedfx#356]
- [x] Make repeated installations of FFMPEG non-mandatory.
- [x] Allow to select existing FFMPEG installation in HLAE / Installer.
- [x] Allow to select static (recommended, faster) and shared (smaller download size) FFMPEG builds.

Edit by @dtugend .

----

`HLAE_Setup.exe` suggests that you can install FFmpeg later.

But `ffmpeg/readme.advancedfx.txt` does not exist.
We can find it in the Zip file, but it does not exist in the installer.

In addition, because of the need of [You-Get](https://github.com/soimort/you-get), I have downloaded FFmpeg and added it to the PATH.

So I hope HLAE can give the option to set FFmpeg address or detect PATH.
Otherwise, repeated “installation” of FFmpeg is a waste of storage space.

Above, thanks

**Comment by dtugend** [comment]
The reason for that is that people are not supposed to change files manually when using the installer inside the program directories managed by the installer, since you are supposed to manage the installation through the installer (unlike `%APPDATA%/HLAE` folder, which is meant to be possible to be modified).

Ideally the installer would be better and allow modifying the options when already installed :/

As a workaround you could use the ZIP version of HLAE, as you already noted, but then you gotta make sure to put it in the a path without special characters (e.g. C:\HLAE) :|

The main purpose of the installer [for me] is to provide a solution for people that would otherwise wrongly install HLAE in a path with special characters, since it prevents that. E.g. some people would put it into Desktop, but the Desktop is inside the User folder and the user folder has special characters, it's supposed to prevent these things (see #65).

The automatic install of FFMPEG and making sure that users have the right .NET installed is only a secondary objective.

To be honest the installer only gets 3 - 4 % of the total downloads [according to GitHub](https://api.github.com/repos/advancedfx/advancedfx/releases/latest), so we might consider to get rid of it until we have a better installer and instead make a warning / info in HLAE when it's in wrong folder and an option inside HLAE to install FFMPEG? What do you think @advancedfx/code @advancedfx/doc ?

**Comment by cherinyy** [comment]
> The reason for that is that people are not supposed to change files manually when using the installer inside the program directories managed by the installer, since you are supposed to manage the installation through the installer (unlike `%APPDATA%/HLAE` folder, which is meant to be possible to be modified).
> 
> Ideally the installer would be better and allow modifying the options when already installed :/
> 
> As a workaround you could use the ZIP version of HLAE, as you already noted, but then you gotta make sure to put it in the a path without special characters (e.g. C:\HLAE) :|
> 
> The main purpose of the installer [for me] is to provide a solution for people that would otherwise wrongly install HLAE in a path with special characters, since it prevents that. E.g. some people would put it into Desktop, but the Desktop is inside the User folder and the user folder has special characters, it's supposed to prevent these things (see #65).
> 
> The automatic install of FFMPEG and making sure that users have the right .NET installed is only a secondary objective.
> 
> To be honest the installer only gets 3 - 4 % of the total downloads [according to GitHub](https://api.github.com/repos/advancedfx/advancedfx/releases/latest), so we might consider to get rid of it until we have a better installer and instead make a warning / info in HLAE when it's in wrong folder and an option inside HLAE to install FFMPEG? What do you think @advancedfx/code @advancedfx/doc ?

This is interesting news, I have not considered that the installer is just a situation that appears for simplicity.

I have replaced the installer with the Zip version.

> What do you think @advancedfx/code @advancedfx/doc ?

I'm sorry, I don't quite understand what you mean, what exactly do you mean?

**Comment by dtugend** [comment]
> I'm sorry, I don't quite understand what you mean, what exactly do you mean?

I was just calling for the HLAE team to give feedback here, but they did through other channels instead.
