### ISSUE TITLE
(csgo) audio is longer than the video ! how to fix !

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#36]
i used to record with HLAE and no problem . but now sound is slow and longer than video 
i hope you understand me and thx

**Comment by dtugend** [comment]
You are probably using Valve's startmovie to record your footage, that command doesn't work properly since a while now anymore.
However you can use HLAE's mirv_streams command to record your audio, for more info see:
http://advancedfx.style-productions.net/forum/viewtopic.php?f=6&t=2170&hilit=audio+mirv_streams
and
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams

**Comment by dtugend** [comment]
Btw, if you use it for simple recordings only, check out this tool: https://csgo-demos-manager.com/docs/movie/getting-started
