### ISSUE TITLE
Engine Error 

### ISSUE THREAD

**Issue by NiklasHolmLauritzen** [advancedfx/advancedfx#374]
When I try to open any demos, it will either freeze in spot and never continue or pop up with the message shown below.
![image](https://user-images.githubusercontent.com/57747224/89153292-e134c800-d564-11ea-9969-20c6365566d0.png)
It depends on where I launch the game if it is launched through HLAE and tries to open a demo the message pops and the standard launch will the game freezes when loading demo. I've been attempting to verify it, but no luck was there so now I'm stuck here.

_I've also sent the issue in the discord server, but since I don't know which is the fastest respond, I did submit the ticket here too._

**Comment by NiklasHolmLauritzen** [comment]
I've also read the same issue from #211, but it does not seem to work unless I did delete incorrect files.

**Comment by dtugend** [comment]
This doesn't sound like a HLAE problem, more like your CS:GO install is in an incosistent state.
1) Right Click CS:GO in Steam Library -> Properties -> On Betas tab make sure "NONE (opt out of all betas)" is selected and not something else, click okay and let it update.
3)  Right Click CS:GO in Steam Library -> Properties -> On LOCAL FILES tab, click "Verify Game Cache" and let it verify and eventually download files.

**Comment by NiklasHolmLauritzen** [comment]
> This doesn't sound like a HLAE problem, more like your CS:GO install is in an incosistent state.
> 
> 1. Right Click CS:GO in Steam Library -> Properties -> On Betas tab make sure "NONE (opt out of all betas)" is selected and not something else, click okay and let it update.
> 2. Right Click CS:GO in Steam Library -> Properties -> On LOCAL FILES tab, click "Verify Game Cache" and let it verify and eventually download files.

Sorry to say but you're wrong I've already checked it before, and it still did not work when I verified the game files. As it was my first reaction.

**Comment by dtugend** [comment]
You probably have two problems. Let's solve the non-HLAE releated one first:

1) Freezing upon playing demo (without HLAE):

When exactly does the demo freeze?

If it freezes upon loading it's probably because your `video.txt` or `video_defaults.txt` in your userconfig folder have queued rendering on 0 (`"setting.mat_queue_mode"		"0"`).

(Edit: Your gaming config might change it to -1, in which case it will crash when started with 0.)

To change this open your both files in `C:\Program Files (x86)\Steam\userdata\<SteamAccountIdHere>\730\local\cfg` and change that line to `"setting.mat_queue_mode"		"-1"`, save and try again.

If this fixes the CS:GO freezing we can continue with fixing HLAE problem (probably you are one of those people that end up with two CS:GO installs after a while and are launching the old one from HLAE).

**Comment by NiklasHolmLauritzen** [comment]
It manages to load and play the demos now by the default/without-HLAE launch.

**Comment by NiklasHolmLauritzen** [comment]
It works now with the HLAE too. Thanks for the support!

**Comment by dtugend** [comment]
Okay, in case it wouldn't have worked that would have been the most likely solution:

- Right click CS:GO in Steam Library -> Properties -> Browse Local files button
- Click in address bar (behind the current folder name) in Windows Explorer Window that opens and copy the full path (e.g. standard is `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive`), it might be similar to current one but still be a bit different.
- paste it into HLAE where the csgo.exe path goes and append `\csgo.exe`
- Try if it works now

If it doesn't work, make sure that your HLAE is really the latest fully updated version:
https://github.com/advancedfx/advancedfx/releases/latest
