### ISSUE TITLE
Afxsource error 

### ISSUE THREAD

**Issue by Metalheadoscar** [advancedfx/advancedfx#375]
(Please search exiting **open and closed** issues first to verify this is a new bug report.)
C:\source\advancedfx\AfxHookSource\addresses.cpp:796

This continuously pops up while trying to open Counter Strike. And without fail will not open anything and leave me in a black screen. 
What does this mean and how can i work around this issue.

**Comment by dtugend** [comment]
1. Make sure you are using latest HLAE version (will have 1.103.1.0 in GUI window title, otherwise it's not latest)
2. Right Click CS:GO in Steam Library -> Properties -> On Betas tab make sure "NONE (opt out of all betas)" is selected and not something else, click okay and let it update.
3. Right Click CS:GO in Steam Library -> Properties -> On LOCAL FILES tab, click "Verify Game Cache" and let it verify and eventually download files.
4. Right click CS:GO in Steam library -> Properties -> Local Files Tab -> Browse Local Files button and copy & paste the full path into HLAE and append \csgo.exe to make sure you are using the right path in HLAE (some people end up with two installs after a while).

**Comment by dtugend** [comment]
Additonally to the above we recommend to use File -> Launch CS:GO instead of Custom Loader.

If you really need Custom Loader, please make sure that last big box contains these:
```
SteamPath=C:\Program Files (x86)\Steam
SteamClientLaunch=1
SteamGameId=730
SteamAppId=730
SteamOverlayGameId=730
```

Please adjust `C:\Program Files (x86)\Steam` to the actual Steam path.

**Comment by dtugend** [comment]
Closing due to no feedback.
