### ISSUE TITLE
mirv_input camera for cs 1.6

### ISSUE THREAD

**Issue by lill1an** [advancedfx/advancedfx#389]
Thank you for this software, I've been using it for years :) I am surprised that you guys added the 'mirv_campath add' it makes a lot easier to make some smooth cinematics. It would be very cool if you'd add the command which I mentioned in the title, so it can let us rotate the camera angle and do even better shots :) Thank you in advance.

**Comment by Dechno1337** [comment]
The main reason that command was made, as far as I know, was because CS:GO doesn't let you move around in a paused demo, while CS 1.6 does. I don't remember exactly the extent of mirv_campath in 1.6; are you unable to edit campaths? One way I think, is to save the campath to a local file, edit the rotation values and then import (load) it in-game.

Also, maybe there are GoldSrc commands to rotate the view(?)

**Comment by lill1an** [comment]
Well, speaking about saving the campath to a local life, which sofwtare can be used to rotate the camera angle using this way? Unfortunately, there are no GoldSrc commands to rotate the view, it is available to rotate the camera using old way, when you have to make campaths with demoedit but mirv_campath cannot be used while doing that.

**Comment by Dechno1337** [comment]
> Well, speaking about saving the campath to a local life, which software can be used to rotate the camera angle using this way?

Just open the file with notepad(++)

**Comment by Dechno1337** [comment]
In case someone missed it, `mirv_roll` was implemented as a way to roll the camera:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_roll

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.151.0
