### ISSUE TITLE
Error with hlae?!!

### ISSUE THREAD

**Issue by jeezuz** [advancedfx/advancedfx#39]
so when I start hlae with custom loader i always get this message https://gyazo.com/bd7d97c779568c9657c07fd7d1ce63f6
 HELP PLS FAST

**Comment by dtugend** [comment]
The error message contains a part that reads solution, please read it.

**Comment by jeezuz** [comment]
I have done every thing it says but it still wont work.

**Comment by dtugend** [comment]
Do you use ESEA Client or FaceIt Client or ChallengeMe.gg? If so you need to also check that they don't keep running in background / quit them properly. Also it can be caused by behavioral anti virus, for example Comodo Cloud Antivirus used to cause that a while ago. If that doesn't solve the problem either then please add me in Steam: https://steamcommunity.com/id/ripieces

**Comment by jeezuz** [comment]
I do have does programs but they are not on or in the background. So I will add u on steam

**Comment by dtugend** [comment]
My email is also on my GitHub profile in case there is a problem with Steam / Windows after adware removal / reboot.

**Comment by dtugend** [comment]
Problem was ChallengeMe.gg + CEVO client (uninstalled both) + a needed reboot, then it worked.
