### ISSUE TITLE
(mirv_pov) CS:GO crashes when attached player disconnects

### ISSUE THREAD

**Issue by nthnwllms** [advancedfx/advancedfx#396]
When you're watching a player using mirv_pov, if the player disconnects, CS:GO closes. No "not responding" or anything. It seems it cannot be bypassed by skipping rounds or using demo_gototick to skip to when the player reconnects. The player seems to hold their index # but their "C_CSPlayer::" value changes after reconnecting.

Ex. [Demo](https://www.hltv.org/matches/2343625/fnatic-vs-mousesports-esl-pro-league-season-12-europe) Dust 2, ropz (mirv_pov 8), end of round 7/beginning of round 8 he disconnects and reconnects.

At the start of the game, his player index prints 
>8 (202.988211): class C_CSPlayer:: :47317000
>playerInfo.xuid: 76561197991272318
>playerInfo.name: ropz
>playerInfo.userID: 29

and when he reconnects it prints
>8 (3224.715072): class C_CSPlayer:: :47251464
>playerInfo.xuid: 76561197991272318
>playerInfo.name: ropz
>playerInfo.userID: 16

**Comment by Js9527** [comment]
it seems not fixed yet, i disconnected at round 3, after i get connected, tht view is fixed at T's bron, I can't change view by skipping rounds

**Comment by dtugend** [comment]
@Js9527 Please open an own new issue then and make sure to provide the following information there:
- download of demo in question
- exact mirv_pov settings used (full command)
- exact HLAE version used (written in HLAE GUI title bar)

**Comment by dtugend** [comment]
Additionally, since unlike this issue you didn't say it crashes for you, please double check that it's not simply just your entity index / player slot number changing:

Use `mirv_listentities isPlayer=1` to check if the number changed after you reconnected (this can happen on non-match-making servers).
If yes, then you will need stop the demo, set the new number with mirv_pov and load the demo a second time for the second part with the new number set.
