### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by BlakeMacca** [advancedfx/advancedfx#4]
When i download it it comes up with **_"Failed - Virus Scan Failed"_**

**Comment by dtugend** [comment]
Which Anti-Virus / Scanner you use?

If it's Sophos, I have had it with them:
http://advancedfx.style-productions.net/forum/viewtopic.php?f=6&t=2058

You can tell them about it here, they basically "trolled" me, because I have no license of them when I tried to report and kept insisting the files I submitted are undetected and stuff like that:
http://www.sophos.com/support/samples/

But might also be a browser plug-in you use, that uses virustotal.com and is set too tight (already blocking for 1 - 2 alerts):
https://www.virustotal.com/en/file/fb18a5cd649466ed8099226b1204e691fc1513cd15da1f9b9840e1c2c9dab3e8/analysis/1497767003/

**Comment by dtugend** [comment]
Closing due to lacking feedback.
