### ISSUE TITLE
cannot load old demos

### ISSUE THREAD

**Issue by stuqedits** [advancedfx/advancedfx#404]
I have searched the already existing topics about this issue, and they did not help.
Story: I did a fresh install of Windows, installed all drivers, installed Steam, installed CS:GO then HLAE
I am trying to load 2015-2016 demos, the loading screen pops up, and the download bar is empty and stuck.
It seems that the game cannot acquire access to download the old maps.
*I have tried the following commands, and they did not fix the issue:
  cl_allowdownload 1
  cl_download_demoplayer 1 and cl_download_demoplayer 2
  cl_downloadfilter all
*I have verified the integrity of the game files
*I have provided a screenshot down below explaining the situation
I could not find any solution on the internet, and I wish I can find help here.
Thanks in advance, stuqedits.
![issue](https://user-images.githubusercontent.com/74831990/99883584-bf9d4080-2c28-11eb-98be-f915bfde3584.PNG)

**Comment by dtugend** [comment]
Are you in Steam offline mode?
Steam needs to be online, otherwise CS:GO can't download maps.

**Comment by stuqedits** [comment]
No , I am in online mode. Also, Steam, CS:GO and HLAE are all up to date, and that's the thing that's bothering me: it's that I can't troubleshoot any further, I seriously cannot think of any other possibilities causing this!

**Comment by dtugend** [comment]
maybe provide a link to one of the demos, so we can check if anything can be dine or if it's an CS:GO problem.

**Comment by stuqedits** [comment]
I have tested several demos, same thing.
https://www.hltv.org/matches/2299501/tsm-vs-liquid-faceit-league-2015-stage-3-finals-at-dh-winter-2015
Here is the link to one of them, thanks for your patience Sir.

**Comment by dtugend** [comment]
The demo you sent works fine for me, it downloads them map.

The problem is also something else probably, since it says "Host_Error: Disconnected".
Would be interesting to know what it says above that.

Enter `version` into the game console when launched from HLAE to see the game version (maybe copy and paste here).
Also which HLAE version are you using?
Are there any error messages (popups / ingame top yellow bar) etc. when launching from HLAE?

Also try to start with a clean config:
Use File -> Launch CS:GO dialogue and enable "mmcfg" folder option and set an empty folder (e.g. mmcfg on your Desktop) and launch from that. If that fixes the problem it's something in your config.

**Comment by stuqedits** [comment]
Yes, it worked.
I have made an empty folder as my mm parent folder and launched the game, and it successfully downloaded the map.
In a way, I can just utilize this method to download the map then go back to my config to load the demo until I find where the problem lies.
Thanks a lot for your help! Much appreciated, have a wonderful day/night.

**Comment by dtugend** [comment]
Are you using customloader?
If yes, then the bottom box must not be empty for CS:GO, it should be:

```
SteamPath=C:\Program Files (x86)\Steam
SteamClientLaunch=1
SteamGameId=730
SteamAppId=730
SteamOverlayGameId=730
```
![screenshot](https://user-images.githubusercontent.com/3610128/99889436-74e5ed80-2c55-11eb-8282-a6c71ca1d208.png)

**Comment by dtugend** [comment]
Is it solved?
