### ISSUE TITLE
mirv_streams/startmovie ?

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#405]
valve fixed the issue when recording using **startmovie** command .!
so i can record using  **startmovie**  or  **mirv_streams** ? right ! no difference ?
because **mirv_streams** commands came when valve made the issues when you record with **startmovie** command !!!!

**Comment by dtugend** [comment]
You can use whichever command you prefer.

There is differences in the way the commands work and the features that are offered:
- startmovie only records when console is closed, mirv_streams always records
- mirv_streams only records the game layer and not console / VGUI overlays (e.g. demoui)
- mirv_streams supports multiple different streams with different effects and different output settings (e.g. to FFMPEG), startmovie only supports the equivalent of one mirv_streams "normal" stream and tga sequence / wav / jpeg sequence / png sequence / avi output

You can read more about mirv_streams here:  
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams

> because mirv_streams commands came when valve made the issues when you record with startmovie command !!!!

This is wrong: mirv_streams was added 2015 already, startmovie sound broke some year(s) after that.

We are very well aware that they fixed it at the beginning of this year, because we happen know the person that submitted the patch that fixes it to them very well, even though the person asked to not be credited for these and other small changes:  
https://blog.counter-strike.net/index.php/2020/01/27853/
