### ISSUE TITLE
CS:GO crash on launch (-panorama -afxDetourPanorama)

### ISSUE THREAD

**Issue by XIIIG** [advancedfx/advancedfx#410]
Hello,

I'm trying to launch CS:GO with the parameters below, but unfortunately it seems like -afxDetourPanorama crashes CS:GO on launch.
`-panorama -afxDetourPanorama`

Is this known issue? 

I have the latest HLAE version - v1.7.1 (2020-12-14T18:18Z)

**Comment by dtugend** [comment]
You only need these command line options if you want to change Panorama UI as described here:
https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

Otherwise just remove them.

Please make sure to read the **Notes** at the end of the article:

Notes:
1) You have to keep `-panorama -afxDetourPanorama` in HLAE's command line. If panorama is not updated, it is sufficient to restart at 9) after you have worked through the list once.
2) Valve is updating HUD and game, so it will be useful to at least write somewhere what exactly you change in HUD.  
We recommend for advanced users to use a version control system (i.e. GIT, see https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) _locally_ to re-apply changes faster (**do not upload to public repositories, this will get you DMCAed by Valve**).
Future updates can break your HUD, etc.  
In case of an HUD update delete panorama.my.zip and start at 1) again.

**Comment by dtugend** [comment]
> I have the latest HLAE version - v1.7.1 (2020-12-14T18:18Z)

That's the latest afx-sfm-scripts version btw, not HLAE.

**Comment by XIIIG** [comment]
Oh! I tried to launch CS:GO with `-panorama -afxDetourPanorama` without having source panorama files in CS:GO folder. 
Now it doesn't crash, thank you.

**Comment by dtugend** [comment]
You can just remove `-panorama -afxDetourPanorama` then as said.
