### ISSUE TITLE
how to rebind "mirv_input camera mod"?

### ISSUE THREAD

**Issue by keon1337** [advancedfx/advancedfx#412]
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_input
i need to change buttons for this mode, and idk where is cfg file!

**Comment by dtugend** [comment]
As explained in #318 this is currently not possible and planned for HLAE 3 instead.

if you only need to rebind keys in order to be able to also use them for s.th. else, please take notice that there is a special key for that purpose:
- Ignore and pass through next key: [CTRL]

Pressing this key will make the next key go through to CS:GO unmodified.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
