### ISSUE TITLE
mirv_streams for TF2

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#417]
As someone who started out editing with TF2, then edited CSGO for 2 years and then planning on returning to TF2 movie making, the lack of mirv_streams causes a very big limitation in creative freedom. Therefore, I think it would be a nice addition to HLAE if mirv_streams were supported to work in TF2.
Thanks

**Comment by balo22** [comment]
I agree.

**Comment by dtugend** [comment]
Some of the team thought it would be a good idea to let you know instead of not replying.

We appreaciate the feature request, but currently there's lots of other stuff to do, so unless someone can contribute it to HLAE (which won't be easy, since a lot of the streams system is CS:GO focused), it won't happen soon in HLAE.

**Comment by dtugend** [comment]
Probably we won't implement this, since there's now Sparkly FX for TF2:
https://github.com/cademtz/sparkly-fx
