### ISSUE TITLE
New HLAE not working

### ISSUE THREAD

**Issue by Smoooooooooth** [advancedfx/advancedfx#44]
This no longer works csgo doesn't even launch and the actual executable HLAE gets deleted after trying to launch. Fix this right now!

**Comment by dtugend** [comment]
This is probably caused by your Antivirus, please add an exception for the folder that contains HLAE.exe or consider using a different one. Be sure to re-download and re-extract HLAE after you addressed the problem with your Anti-Virus since it might be deleting other required files as well like the injector.exe (there's two  of them, the one who n the x64 sub-folder doesn't matter).

**Comment by Smoooooooooth** [comment]
I got it working now. Anyway cheers for the heads up
