### ISSUE TITLE
Ban?

### ISSUE THREAD

**Issue by asumika** [advancedfx/advancedfx#48]
Ok, so I was recording with hlae on my alt account and then forgot the launcher on. After that, I logged on my main and queued for dm on vac secured servers, while having launcher on the background (NOTE: not injected). Will I get banned for this or am I fine?

**Comment by dtugend** [comment]
It should be fine: The HLAE.exe is only the launcher GUI, the game is only modified when it's injected by launching it from HLAE. Since you launched the game not from HLAE when gaming it should be fine.
Also in default HLAE settings the game would warn you when launching from HLAE ("insecure mode") and should even prevent connections to VAC secured servers in insecure mode (wouldn't relay on it though).
