### ISSUE TITLE
Unable to use mirv_input camera

### ISSUE THREAD

**Issue by zxcv0102** [advancedfx/advancedfx#5]
When I run MIRV_input camera ...I can move around and by pressing Ctrl I can add campaths ...and mirv_campath save campath and mirv_campath save campath is also working ...but when I exit mirv_input camera and type mirv_campath enable 1.....it says "campath enabled but not properly evaluated .do u add enough campaths?"
And also I cannot free roam in 3rd person view...don't know why although I am not having demo paused ...please help.

**Comment by dtugend** [comment]
1) Regarding the campath problem:

There are several keys that are reserved by mirv_input camera, CTRL is one of them, the full list can be found here: https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_input#mirv_input-camera

So use some non-reserved key please, also not P, that one cannot be used due to a bug/feature in CS:GO.

2) Regarding the 3rd person view:

How do you switch into 3rd person view? What do you mean by not being able to roam freely? I assume you are not using mirv_input camera during that? The game has several 3rd person modes, one where the camera follows the player and one where you can roam completely free (spec_mode 5 or maybe 6 I think).

**Comment by zxcv0102** [comment]
Regarding campath problem...I when I press Ctrl ...then I use mirv_campath add to Add the campaths...the problem is I can't use mirv_campath enable 1 ....means campath doesn't start in demo :(


Regarding 3rd person view ...yes I am talking about free roam...I can't move in free roam with my w,a,s,d keys ...I am stuck at one place ...don't know why...earlier everything was working fine ..


Can it be because of my movie making config...can u provide me with good movie making config?

**Comment by dtugend** [comment]
Which key have you bound "**mirv_campath add**" to?
Most likely your bind is not not working, meaning no pints are added, you can check with
**mirv_campath print**
Depending on they key you bound it too, it might be not required to press CTRL (if it's not used by mirv_input camera).

And yes it can be because of your movie making config, or because the demo is paused (you said it's not, but if you do pause it, you need to use mirv_input camera, also if the demo is paused and you add points at the same demo time, the old point at the same time will be overwritten).

Maybe you find these tutorials helpful:
https://www.youtube.com/watch?v=9AFXPESOEz0
https://www.reddit.com/r/GlobalOffensive/comments/2r0zkg/as_requested_ultimate_csgo_moviemaking_guide_by/
Those have movie making configs linked, but maybe you can find a better one from some movie maker you like.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
