### ISSUE TITLE
Blue Shadow Bug

### ISSUE THREAD

**Issue by UnknownFME** [advancedfx/advancedfx#642]
Experiencing the old shadow bug from 2016/17 after executing afx/wh config. No issue before executing the config. Only tested on live GOTV, not sure if bug is present in recorded demo's

**Comment by dtugend** [comment]
Maybe it's related to this: https://github.com/advancedfx/advancedfx/wiki/Fix-black-models-%28e.g.-wagons-on-de_train%29-on-old-demos-maps

On _some_ older maps (demos) your need `mirv_cvar_unhide_all; r_staticlight_streams 1` on newer maps you need the default `mirv_cvar_unhide_all; r_staticlight_streams 3`.

**Comment by UnknownFME** [comment]
Of course. Seems to be a shading issue as it also sometimes affects plants. Just to be clear this is not an issue when AfxWhPreview is enabled but only when the config afx/wh is executed.
![2021-04-30 18_30_48-Parsec](https://user-images.githubusercontent.com/66140850/116725642-7f659980-a9e2-11eb-8ce2-ea951540e8e0.png)
![2021-04-30 18_31_01-Parsec](https://user-images.githubusercontent.com/66140850/116725645-8096c680-a9e2-11eb-9fa4-f5e8e70479a1.png)
![2021-04-30 18_28_04-Parsec](https://user-images.githubusercontent.com/66140850/116725646-812f5d00-a9e2-11eb-90b5-5162b6628afb.png)

**Comment by dtugend** [comment]
I am not sure yet how to solve this 100%.

The problem is caused by the usuage of `cl_modelfastpath 0` in the config in order to improve detection of ragdolls / dead players.

A temporary work around is to change afx/wh.cfg as follows:

## Live observing

This assumes you use afxWhPreview to bring the WH into previw and afWhPreviewEnd when disabling it.

Change from:
```
alias afxWhPreview "mirv_streams preview afxWh"
alias afxWhPreviewEnd "mirv_streams previewEnd"
```

Change to:
```
alias afxWhPreview "mirv_streams preview afxWh; cl_modelfastpath 0; cl_tlucfastpath 0; cl_brushfastpath 0"
alias afxWhPreviewEnd "cl_modelfastpath 1; cl_tlucfastpath 1; cl_brushfastpath 1; mirv_streams previewEnd"
```

And remove these lines at the end:
```
cl_modelfastpath 0
cl_tlucfastpath 0
cl_brushfastpath 0
```

## Mainly for movie makers (will crash when you change map / disconnect while wh stream is in preview):

Remove these lines at the end:
```
cl_modelfastpath 0
cl_tlucfastpath 0
cl_brushfastpath 0
```

Add these lines at the end:
```
mirv_streams edit afxWh attachCommands cl_modelfastpath 0; cl_tlucfastpath 0; cl_brushfastpath 0
mirv_streams edit afxWh detachCommands cl_modelfastpath 1; cl_tlucfastpath 1; cl_brushfastpath 1
```

----

The problem with enhanced entity detetction (requiring fastpath 0) is not trivial, I have thought multiple times how to detect them properly with fastpath 1, but it's not easy at all.

**Comment by UnknownFME** [comment]
Seems to have fixed it. Thank you!
