### ISSUE TITLE
Loader Failed | Code: 2001

### ISSUE THREAD

**Issue by kalinzange** [advancedfx/advancedfx#69]
When I try launch CSGO for the first time, shows Error:

```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```

What can I do to fix this? I tried both HLAE (Paronama and Non-Paronama) and run as admin.

CSGO Launch Settings:
![2dc95b0f1b794b943a7af06e735b1326](https://user-images.githubusercontent.com/38161086/42240120-2c19060c-7efe-11e8-905c-bac1ca2b0182.png)

Error:
![ccac7518cb463fda04bc87e10080fc5d](https://user-images.githubusercontent.com/38161086/42240149-44a7ede6-7efe-11e8-9b60-7df8b48209fd.png)

**Comment by dtugend** [comment]
Make sure that no Anti Cheat is running (ESEA Client / FaceIt Anti Cheat / ChallengeMe dot gg ).

Additionally please use the "normal" HLAE version ("Current release [....]") from the official download page (link: https://advancedfx.org/download/) advancedfx.org/download/ if you are unsure - unless you are signed into CS:GO #PanoramaUI beta. 
(Since it already went wrong for some.)

**Comment by dtugend** [comment]
No feedback within 9+days, closing.
