### ISSUE TITLE
Cant launch csgo

### ISSUE THREAD

**Issue by Stop-it1** [advancedfx/advancedfx#79]
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```

**Comment by dtugend** [comment]
Hi, please disable ESEA Client / Faceit AntiCheat Client / ChallengeMe.gg client before launching from HLAE.

Also please research closed issue next time before opening a new one.

**Comment by Stop-it1** [comment]
I did this but it still doesnt work thats why i wrote a issue and ive tried turing off my antivirus and everything

**Comment by Stop-it1** [comment]
That wasnt the issue it was my windows detecting the injector as a virus and deleting the exe

**Comment by dtugend** [comment]
Thank you for reporting back.
Please make sure to update your Windows Defender definitions to the latest, they are or were probably outdated then, the newer definitions have HLAE cleared.

I am closing the  issue, since you indicated it's solved for you now, if it's not solved yet, please comment here, so we can re-open it.
