### ISSUE TITLE
mirv_streams record start won't create files in the directory

### ISSUE THREAD

**Issue by kubak01** [advancedfx/advancedfx#9]
```] mirv_streams record start
Starting recording ... done.
Recording to "G:\csgo\raw\take0001".
The audio might be empty, because Valve removed code from startmovie for appending data to the WAV file!
Started recording movie, frames will record after console is cleared...

] mirv_streams record end
Finishing recording ... done.
Stopped recording movie...
```

The only thing that sits in the folder is a bugged audio.wav file,
don't care about it tho. I want frames the most but they do not create.

Tried it on a custom folder (g:\csgo\raw\) but also tried it without custom folder (so in game's folder)

both failed

Any thoughs?

eddit: startmovie works normally

**Comment by dtugend** [comment]
Sounds like you either didn't add any streams to be recorded or set their record property to 0 (so they won't be recorded).

If you are new to mirv_streams, please read this manual entry: https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_streams Or search for some tutorial on YouTube please.

Edit: Also startmovie won't record audio properly either (mirv_streams uses startmovie wav to record the audio), it's a bug since the 7/7/2016 CS:GO update.

**Comment by Snooober** [comment]
@kubak01 hey I had the same question and have been looking forever for an answer. @ripieces is correct - you need to add a normal stream: "mirv_streams add normal myName" then you should be good to go.

I never saw this mentioned on the youtube tutorials that I watched unfortunately :/

**Comment by kubak01** [comment]
Yeah,

reoslved. Thanks @ripieces
