### ISSUE TITLE
Automatically record video

### ISSUE THREAD

**Issue by nnnet** [advancedfx/advancedfx#96]
Prompt, pls, whether it is possible to make automatic creation of video,
if known:
- camera coordinates / (key), i.e. where it should be and where to look
- tick_start and tick_end in the *.dem-file
 
In the ideal run "script" with the parameters that:
- will launch HLAE,
-  HLAE will start CS GO
- CS GO will load the required demo
- the camera will be installed at XYZ from the script
- go to the desired tick
- incl. camera for recording
- stop recording on tick_end
- stop CS GO and HLAE

is it possible? How?
Or can there be other ways to automatically record video
without manually entering commands?

Thanx

**Comment by dtugend** [comment]
**Yes it is possible:**

- camera coordinates / (key), i.e. where it should be and where to look -> **spec_goto console command**
- tick_start and tick_end in the *.dem-file -> **use demo_gototick in vdm files or mirv_cmd to schedule commands to be executed on a certain tick, use +exec yourcfg.cfg to load the inital cfg**  

- In the ideal run "script" with the parameters that: [....] ->https://github.com/advancedfx/advancedfx/wiki/HLAE-Interfaces#command-line-parameters

There are already tools and websites doing parts of that, for example:
- https://csgo-demos-manager.com/ (tool)
- https://www.igmdb.org/
- https://www.outrekt.com/

Since you seem to be new to HLAE / moviemaking, here is a guide that might be useful later on, depending on what you need to do:
https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos

**Comment by dtugend** [comment]
Hint in case it's hard to figure out for you and it was not intended: Look up the word "prompt" in a proper dictionary (not Google Translate).

**Comment by nnnet** [comment]
@dtugend  thank you, this is what I need
But :)
Here https://csgo-demos-manager.com/docs/movie/getting-started
https://youtu.be/83anQLF9z18
it is shown how with the help of the GUI csgo-demos-manager a video is made in the HLAE
Assume that HLAE starts with certain options and files-cfg from csgo-demos-manager.
Where can I find an example of how to do the same without GUI csgo-demos-manager?
Those. an example of these commands(may be bat-files) and files-cfg that make a video?

Think the example would be very useful in the HLAE documentation.

Thanx

**Comment by dtugend** [comment]
1) CS:GO Demos Manager is open source: https://github.com/akiver/CSGO-Demos-Manager
2) The page I linked above already has a few examples: https://github.com/advancedfx/advancedfx/wiki/HLAE-Interfaces
3) You can either use VDM files to execute your commands like CS:GO Demos Manager does or you can use the mirv_cmd HLAE console command. I recommend the former. Both are not well documented, I recommend to use both https://developer.valvesoftware.com/wiki/Demo_Recording_Tools#Demo_editor (CS:GO Demos Manager uses them too) and then look at the files created. https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_cmd

**Comment by dtugend** [comment]
Do you have further questions?
I am closing the issue until then, feel free to reply if you have further questions.
